#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_set_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                            const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("add", 2, "(s: set, value: T)", named::set(), {p.set, p.any}),
            m.fn("concat", 2, "(a: set, b: set)", named::set(), {p.set, p.set}),
            m.fn("contains", 2, "(s: set, value: T)", R::boolean_type(), {p.set, p.any}),
            m.fn("difference", 2, "(a: set, b: set)", named::set(), {p.set, p.set}),
            m.fn("equals", 2, "(a: set, b: set)", R::boolean_type(), {p.set, p.set}),
            m.fn("each", 2, "(s: set, f: func(T) -> none)", R::result(R::none_type()),
                 {p.set, p.func}),
            m.fn("filter", 2, "(s: set, f: func(T) -> boolean)", R::result(named::set()),
                 {p.set, p.func}),
            m.fn("from_array", 1, "(arr: array<T>)", named::set(), {p.array_any}),
            m.fn("map", 2, "(s: set, f: func(T) -> U)", R::result(named::set()), {p.set, p.func}),
            m.fn("intersection", 2, "(a: set, b: set)", named::set(), {p.set, p.set}),
            m.fn("is_disjoint", 2, "(a: set, b: set)", R::boolean_type(), {p.set, p.set}),
            m.fn("is_empty", 1, "(s: set)", R::boolean_type(), {p.set}),
            m.fn("is_subset", 2, "(a: set, b: set)", R::boolean_type(), {p.set, p.set}),
            m.fn("is_superset", 2, "(a: set, b: set)", R::boolean_type(), {p.set, p.set}),
            m.fn("length", 1, "(s: set)", R::integer_type(), {p.set}),
            m.fn("new", 0, "()", named::set(), {}),
            m.fn("partition", 2, "(s: set, f: func(T) -> boolean)",
                 R::result(R::tuple({named::set(), named::set()})), {p.set, p.func}),
            m.fn("reduce", 3, "(s: set, initial: U, f: func(U, T) -> U)", R::result_any(),
                 {p.set, p.any, p.func}),
            m.fn("remove", 2, "(s: set, value: T)", named::set(), {p.set, p.any}),
            m.fn("symmetric_difference", 2, "(a: set, b: set)", named::set(), {p.set, p.set}),
            m.fn("to_array", 1, "(s: set)", R::array_any(), {p.set}),
            m.fn("union", 2, "(a: set, b: set)", named::set(), {p.set, p.set}),
        });
}

void register_queue_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                              const ParamShorthands& p) {
    append_specs(specs,
                 {
                     m.fn("concat", 2, "(a: queue, b: queue)", named::queue(), {p.queue, p.queue}),
                     m.fn("all", 2, "(q: queue, f: func(T) -> boolean)", R::result_boolean(),
                          {p.queue, p.func}),
                     m.fn("any", 2, "(q: queue, f: func(T) -> boolean)", R::result_boolean(),
                          {p.queue, p.func}),
                     m.fn("contains", 2, "(q: queue, value: T)", R::boolean_type(),
                          {p.queue, p.any}),
                     m.fn("count", 2, "(q: queue, f: func(T) -> boolean)", R::result_integer(),
                          {p.queue, p.func}),
                     m.fn("dequeue", 1, "(q: queue)", R::result_any(), {p.queue}),
                     m.fn("each", 2, "(q: queue, f: func(T) -> none)", R::result(R::none_type()),
                          {p.queue, p.func}),
                     m.fn("enqueue", 2, "(q: queue, value: T)", named::queue(), {p.queue, p.any}),
                     m.fn("filter", 2, "(q: queue, f: func(T) -> boolean)",
                          R::result(named::queue()), {p.queue, p.func}),
                     m.fn("find", 2, "(q: queue, f: func(T) -> boolean)", R::result_any(),
                          {p.queue, p.func}),
                     m.fn("from_array", 1, "(arr: array<T>)", named::queue(), {p.array_any}),
                     m.fn("is_empty", 1, "(q: queue)", R::boolean_type(), {p.queue}),
                     m.fn("length", 1, "(q: queue)", R::integer_type(), {p.queue}),
                     m.fn("map", 2, "(q: queue, f: func(T) -> U)", R::result(named::queue()),
                          {p.queue, p.func}),
                     m.fn("new", 0, "()", named::queue(), {}),
                     m.fn("partition", 2, "(q: queue, f: func(T) -> boolean)",
                          R::result(R::tuple({named::queue(), named::queue()})), {p.queue, p.func}),
                     m.fn("peek", 1, "(q: queue)", R::result_any(), {p.queue}),
                     m.fn("reduce", 3, "(q: queue, initial: U, f: func(U, T) -> U)",
                          R::result_any(), {p.queue, p.any, p.func}),
                     m.fn("reverse", 1, "(q: queue)", named::queue(), {p.queue}),
                     m.fn("to_array", 1, "(q: queue)", R::array_any(), {p.queue}),
                 });
}

void register_stack_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                              const ParamShorthands& p) {
    append_specs(specs,
                 {
                     m.fn("concat", 2, "(a: stack, b: stack)", named::stack(), {p.stack, p.stack}),
                     m.fn("each", 2, "(s: stack, f: func(T) -> none)", R::result(R::none_type()),
                          {p.stack, p.func}),
                     m.fn("filter", 2, "(s: stack, f: func(T) -> boolean)",
                          R::result(named::stack()), {p.stack, p.func}),
                     m.fn("from_array", 1, "(arr: array<T>)", named::stack(), {p.array_any}),
                     m.fn("is_empty", 1, "(s: stack)", R::boolean_type(), {p.stack}),
                     m.fn("length", 1, "(s: stack)", R::integer_type(), {p.stack}),
                     m.fn("map", 2, "(s: stack, f: func(T) -> U)", R::result(named::stack()),
                          {p.stack, p.func}),
                     m.fn("new", 0, "()", named::stack(), {}),
                     m.fn("partition", 2, "(s: stack, f: func(T) -> boolean)",
                          R::result(R::tuple({named::stack(), named::stack()})), {p.stack, p.func}),
                     m.fn("peek", 1, "(s: stack)", R::result_any(), {p.stack}),
                     m.fn("pop", 1, "(s: stack)", R::result_any(), {p.stack}),
                     m.fn("push", 2, "(s: stack, value: T)", named::stack(), {p.stack, p.any}),
                     m.fn("reduce", 3, "(s: stack, initial: U, f: func(U, T) -> U)",
                          R::result_any(), {p.stack, p.any, p.func}),
                     m.fn("to_array", 1, "(s: stack)", R::array_any(), {p.stack}),
                 });
}

void register_linked_list_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                    const ParamShorthands& p) {
    append_specs(
        specs, {
                   m.fn("append", 2, "(list: linked_list, value: T)", named::linked_list(),
                        {p.linked_list, p.any}),
                   m.fn("at", 2, "(list: linked_list, index: integer)", R::result_any(),
                        {p.linked_list, p.integer}),
                   m.fn("concat", 2, "(a: linked_list, b: linked_list)", named::linked_list(),
                        {p.linked_list, p.linked_list}),
                   m.fn("contains", 2, "(list: linked_list, value: T)", R::boolean_type(),
                        {p.linked_list, p.any}),
                   m.fn("each", 2, "(list: linked_list, f: func(T) -> none)",
                        R::result(R::none_type()), {p.linked_list, p.func}),
                   m.fn("filter", 2, "(list: linked_list, f: func(T) -> boolean)",
                        R::result(named::linked_list()), {p.linked_list, p.func}),
                   m.fn("find", 2, "(list: linked_list, f: func(T) -> boolean)", R::result_any(),
                        {p.linked_list, p.func}),
                   m.fn("first", 1, "(list: linked_list)", R::result_any(), {p.linked_list}),
                   m.fn("from_array", 1, "(arr: array<T>)", named::linked_list(), {p.array_any}),
                   m.fn("insert_at", 3, "(list: linked_list, index: integer, value: T)",
                        R::result(named::linked_list()), {p.linked_list, p.integer, p.any}),
                   m.fn("is_empty", 1, "(list: linked_list)", R::boolean_type(), {p.linked_list}),
                   m.fn("last", 1, "(list: linked_list)", R::result_any(), {p.linked_list}),
                   m.fn("length", 1, "(list: linked_list)", R::integer_type(), {p.linked_list}),
                   m.fn("map", 2, "(list: linked_list, f: func(T) -> U)",
                        R::result(named::linked_list()), {p.linked_list, p.func}),
                   m.fn("new", 0, "()", named::linked_list(), {}),
                   m.fn("partition", 2, "(list: linked_list, f: func(T) -> boolean)",
                        R::result(R::tuple({named::linked_list(), named::linked_list()})),
                        {p.linked_list, p.func}),
                   m.fn("prepend", 2, "(list: linked_list, value: T)", named::linked_list(),
                        {p.linked_list, p.any}),
                   m.fn("push", 2, "(list: linked_list, value: T)", named::linked_list(),
                        {p.linked_list, p.any}),
                   m.fn("reduce", 3, "(list: linked_list, initial: U, f: func(U, T) -> U)",
                        R::result_any(), {p.linked_list, p.any, p.func}),
                   m.fn("remove_at", 2, "(list: linked_list, index: integer)",
                        R::result(named::linked_list()), {p.linked_list, p.integer}),
                   m.fn("remove_first", 1, "(list: linked_list)", R::result(named::linked_list()),
                        {p.linked_list}),
                   m.fn("remove_last", 1, "(list: linked_list)", R::result(named::linked_list()),
                        {p.linked_list}),
                   m.fn("reverse", 1, "(list: linked_list)", named::linked_list(), {p.linked_list}),
                   m.fn("sort", 2, "(list: linked_list, f: func(T, T) -> boolean)",
                        R::result(named::linked_list()), {p.linked_list, p.func}),
                   m.fn("to_array", 1, "(list: linked_list)", R::array_any(), {p.linked_list}),
                   m.fn("unique", 1, "(list: linked_list)", named::linked_list(), {p.linked_list}),
                   m.fn("zip", 2, "(a: linked_list, b: linked_list)", named::linked_list(),
                        {p.linked_list, p.linked_list}),
                   m.fn("all", 2, "(list: linked_list, f: func(T) -> boolean)", R::result_boolean(),
                        {p.linked_list, p.func}),
                   m.fn("any", 2, "(list: linked_list, f: func(T) -> boolean)", R::result_boolean(),
                        {p.linked_list, p.func}),
                   m.fn("count", 2, "(list: linked_list, f: func(T) -> boolean)",
                        R::result_integer(), {p.linked_list, p.func}),
                   m.fn("take", 2, "(list: linked_list, n: integer)", named::linked_list(),
                        {p.linked_list, p.integer}),
                   m.fn("drop", 2, "(list: linked_list, n: integer)", named::linked_list(),
                        {p.linked_list, p.integer}),
                   m.fn("take_while", 2, "(list: linked_list, f: func(T) -> boolean)",
                        R::result(named::linked_list()), {p.linked_list, p.func}),
                   m.fn("drop_while", 2, "(list: linked_list, f: func(T) -> boolean)",
                        R::result(named::linked_list()), {p.linked_list, p.func}),
                   m.fn("min", 1, "(list: linked_list)", R::result_any(), {p.linked_list}),
                   m.fn("max", 1, "(list: linked_list)", R::result_any(), {p.linked_list}),
                   m.fn("sum", 1, "(list: linked_list)", R::result_number(), {p.linked_list}),
                   m.fn("tail", 1, "(list: linked_list)", R::result(named::linked_list()),
                        {p.linked_list}),
                   m.fn("uncons", 1, "(list: linked_list)",
                        R::result(R::tuple({R::any_type(), named::linked_list()})), {p.linked_list}),
               });
}

void register_hash_set_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                 const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("add", 2, "(s: hash_set, value: T)", named::hash_set(), {p.hash_set, p.any}),
            m.fn("all", 2, "(s: hash_set, f: func(T) -> boolean)", R::result_boolean(),
                 {p.hash_set, p.func}),
            m.fn("any", 2, "(s: hash_set, f: func(T) -> boolean)", R::result_boolean(),
                 {p.hash_set, p.func}),
            m.fn("contains", 2, "(s: hash_set, value: T)", R::boolean_type(), {p.hash_set, p.any}),
            m.fn("count", 2, "(s: hash_set, f: func(T) -> boolean)", R::result_integer(),
                 {p.hash_set, p.func}),
            m.fn("difference", 2, "(a: hash_set, b: hash_set)", named::hash_set(),
                 {p.hash_set, p.hash_set}),
            m.fn("equals", 2, "(a: hash_set, b: hash_set)", R::boolean_type(),
                 {p.hash_set, p.hash_set}),
            m.fn("each", 2, "(s: hash_set, f: func(T) -> none)", R::result(R::none_type()),
                 {p.hash_set, p.func}),
            m.fn("filter", 2, "(s: hash_set, f: func(T) -> boolean)", R::result(named::hash_set()),
                 {p.hash_set, p.func}),
            m.fn("find", 2, "(s: hash_set, f: func(T) -> boolean)", R::result_any(),
                 {p.hash_set, p.func}),
            m.fn("from_array", 1, "(arr: array<T>)", named::hash_set(), {p.array_any}),
            m.fn("map", 2, "(s: hash_set, f: func(T) -> U)", R::result(named::hash_set()),
                 {p.hash_set, p.func}),
            m.fn("from_set", 1, "(s: set)", named::hash_set(), {p.set}),
            m.fn("intersection", 2, "(a: hash_set, b: hash_set)", named::hash_set(),
                 {p.hash_set, p.hash_set}),
            m.fn("is_disjoint", 2, "(a: hash_set, b: hash_set)", R::boolean_type(),
                 {p.hash_set, p.hash_set}),
            m.fn("is_empty", 1, "(s: hash_set)", R::boolean_type(), {p.hash_set}),
            m.fn("is_subset", 2, "(a: hash_set, b: hash_set)", R::boolean_type(),
                 {p.hash_set, p.hash_set}),
            m.fn("is_superset", 2, "(a: hash_set, b: hash_set)", R::boolean_type(),
                 {p.hash_set, p.hash_set}),
            m.fn("length", 1, "(s: hash_set)", R::integer_type(), {p.hash_set}),
            m.fn("new", 0, "()", named::hash_set(), {}),
            m.fn("partition", 2, "(s: hash_set, f: func(T) -> boolean)",
                 R::result(R::tuple({named::hash_set(), named::hash_set()})), {p.hash_set, p.func}),
            m.fn("reduce", 3, "(s: hash_set, initial: U, f: func(U, T) -> U)", R::result_any(),
                 {p.hash_set, p.any, p.func}),
            m.fn("remove", 2, "(s: hash_set, value: T)", named::hash_set(), {p.hash_set, p.any}),
            m.fn("symmetric_difference", 2, "(a: hash_set, b: hash_set)", named::hash_set(),
                 {p.hash_set, p.hash_set}),
            m.fn("to_array", 1, "(s: hash_set)", R::array_any(), {p.hash_set}),
            m.fn("to_set", 1, "(s: hash_set)", named::set(), {p.hash_set}),
            m.fn("union", 2, "(a: hash_set, b: hash_set)", named::hash_set(),
                 {p.hash_set, p.hash_set}),
        });
}

} // namespace luma::stdlib::detail
