#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_binary_tree_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                    const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("all", 2, "(tree: binary_tree, f: func(T) -> boolean)", R::result_boolean(),
                 {p.binary_tree, p.func}),
            m.fn("any", 2, "(tree: binary_tree, f: func(T) -> boolean)", R::result_boolean(),
                 {p.binary_tree, p.func}),
            m.fn("balance", 1, "(tree: binary_tree)", named::binary_tree(), {p.binary_tree}),
            m.fn("ceiling_value", 2, "(tree: binary_tree, value: T)", R::result_any(),
                 {p.binary_tree, p.any}),
            m.fn("contains", 2, "(tree: binary_tree, value: T)", R::boolean_type(),
                 {p.binary_tree, p.any}),
            m.fn("count", 2, "(tree: binary_tree, f: func(T) -> boolean)", R::result_integer(),
                 {p.binary_tree, p.func}),
            m.fn("each", 2, "(tree: binary_tree, f: func(T) -> void)",
                 R::result(named::binary_tree()), {p.binary_tree, p.func}),
            m.fn("equals", 2, "(a: binary_tree, b: binary_tree)", R::boolean_type(),
                 {p.binary_tree, p.binary_tree}),
            m.fn("filter", 2, "(tree: binary_tree, f: func(T) -> boolean)",
                 R::result(named::binary_tree()), {p.binary_tree, p.func}),
            m.fn("find", 2, "(tree: binary_tree, f: func(T) -> boolean)",
                 R::result(R::optional_any()), {p.binary_tree, p.func}),
            m.fn("floor_value", 2, "(tree: binary_tree, value: T)", R::result_any(),
                 {p.binary_tree, p.any}),
            m.fn("from_array", 1, "(arr: array<T>)", named::binary_tree(), {p.array_any}),
            m.fn("height", 1, "(tree: binary_tree)", R::integer_type(), {p.binary_tree}),
            m.fn("inorder", 1, "(tree: binary_tree)", R::array_any(), {p.binary_tree}),
            m.fn("insert", 2, "(tree: binary_tree, value: T)", named::binary_tree(),
                 {p.binary_tree, p.any}),
            m.fn("is_balanced", 1, "(tree: binary_tree)", R::boolean_type(), {p.binary_tree}),
            m.fn("is_empty", 1, "(tree: binary_tree)", R::boolean_type(), {p.binary_tree}),
            m.fn("length", 1, "(tree: binary_tree)", R::integer_type(), {p.binary_tree}),
            m.fn("level_order", 1, "(tree: binary_tree)", R::array_any(), {p.binary_tree}),
            m.fn("map", 2, "(tree: binary_tree, f: func(T) -> U)", R::result(named::binary_tree()),
                 {p.binary_tree, p.func}),
            m.fn("max", 1, "(tree: binary_tree)", R::result_any(), {p.binary_tree}),
            m.fn("min", 1, "(tree: binary_tree)", R::result_any(), {p.binary_tree}),
            m.fn("new", 0, "()", named::binary_tree()),
            m.fn("partition", 2, "(tree: binary_tree, f: func(T) -> boolean)",
                 R::result(R::tuple({named::binary_tree(), named::binary_tree()})),
                 {p.binary_tree, p.func}),
            m.fn("postorder", 1, "(tree: binary_tree)", R::array_any(), {p.binary_tree}),
            m.fn("predecessor", 2, "(tree: binary_tree, value: T)", R::result_any(),
                 {p.binary_tree, p.any}),
            m.fn("preorder", 1, "(tree: binary_tree)", R::array_any(), {p.binary_tree}),
            m.fn("reduce", 3, "(tree: binary_tree, initial: U, f: func(U, T) -> U)",
                 R::result_any(), {p.binary_tree, p.any, p.func}),
            m.fn("remove", 2, "(tree: binary_tree, value: T)", named::binary_tree(),
                 {p.binary_tree, p.any}),
            m.fn("successor", 2, "(tree: binary_tree, value: T)", R::result_any(),
                 {p.binary_tree, p.any}),
            m.fn("to_array", 1, "(tree: binary_tree)", R::array_any(), {p.binary_tree}),
            m.fn("union", 2, "(a: binary_tree, b: binary_tree)", named::binary_tree(),
                 {p.binary_tree, p.binary_tree}),
        });
}

void register_graph_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                              const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.variadic_fn("add_edge", 3, "(g: graph, from: string, to: string, weight?: number)",
                          named::graph(), {p.graph, p.string, p.string}),
            m.fn("add_vertex", 2, "(g: graph, name: string)", named::graph(), {p.graph, p.string}),
            m.fn("all_pairs_shortest_paths", 1, "(g: graph)",
                 R::result(R::dict(R::dict(R::number_type()))), {p.graph}),
            m.fn("breadth_first_search", 2, "(g: graph, start: string)",
                 R::result(R::array(R::string_type())), {p.graph, p.string}),
            m.fn("connected_components", 1, "(g: graph)",
                 R::result(R::array(R::array(R::string_type()))), {p.graph}),
            m.fn("degree", 2, "(g: graph, name: string)", R::result_integer(), {p.graph, p.string}),
            m.fn("depth_first_search", 2, "(g: graph, start: string)",
                 R::result(R::array(R::string_type())), {p.graph, p.string}),
            m.fn("directed", 0, "()", named::graph()),
            m.fn("edge_count", 1, "(g: graph)", R::integer_type(), {p.graph}),
            m.fn("edge_weight", 3, "(g: graph, from: string, to: string)", R::result_number(),
                 {p.graph, p.string, p.string}),
            m.fn("edges", 1, "(g: graph)", R::array(named::edge()), {p.graph}),
            m.fn("has_cycle", 1, "(g: graph)", R::boolean_type(), {p.graph}),
            m.fn("has_edge", 3, "(g: graph, from: string, to: string)", R::boolean_type(),
                 {p.graph, p.string, p.string}),
            m.fn("has_vertex", 2, "(g: graph, name: string)", R::boolean_type(),
                 {p.graph, p.string}),
            m.fn("is_directed", 1, "(g: graph)", R::boolean_type(), {p.graph}),
            m.fn("minimum_spanning_tree", 1, "(g: graph)", R::result(named::graph()), {p.graph}),
            m.fn("neighbors", 2, "(g: graph, name: string)", R::result(R::array(R::string_type())),
                 {p.graph, p.string}),
            m.fn("remove_edge", 3, "(g: graph, from: string, to: string)", named::graph(),
                 {p.graph, p.string, p.string}),
            m.fn("remove_vertex", 2, "(g: graph, name: string)", named::graph(),
                 {p.graph, p.string}),
            m.fn("shortest_path", 3, "(g: graph, from: string, to: string)",
                 R::result(R::array(R::string_type())), {p.graph, p.string, p.string}),
            m.fn("shortest_path_detailed", 3, "(g: graph, from: string, to: string)",
                 R::result(named::path()), {p.graph, p.string, p.string}),
            m.fn("strongly_connected_components", 1, "(g: graph)",
                 R::result(R::array(R::array(R::string_type()))), {p.graph}),
            m.fn("to_adjacency_list", 1, "(g: graph)", R::dict(R::array(R::string_type())),
                 {p.graph}),
            m.fn("topological_sort", 1, "(g: graph)", R::result(R::array(R::string_type())),
                 {p.graph}),
            m.fn("undirected", 0, "()", named::graph()),
            m.fn("vertex_count", 1, "(g: graph)", R::integer_type(), {p.graph}),
            m.fn("vertices", 1, "(g: graph)", R::array_string(), {p.graph}),
        });
}

} // namespace luma::stdlib::detail
