#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_math_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                             const ParamShorthands& p) {
    append_specs(
        specs,
        {
            // Some Math functions document "integer | number" in the params string
            // because both types are accepted by the user. The param_types use p.number
            // (number) because the type checker implicitly coerces integer to number.
            m.fn("absolute", 1, "(value: integer | number)", R::result_number(), {p.number}),
            m.variadic_fn("approximately_equal", 2, "(a: number, b: number, epsilon?: number)",
                          R::boolean_type(), {p.number, p.number}),
            m.fn("arc_cosine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("arc_sine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("arc_tangent", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("angle_difference", 2, "(a: number, b: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("ceil", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("combinations", 2, "(n: integer, k: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("complex", 2, "(real: number, imaginary: number)", named::complex(),
                 {p.number, p.number}),
            m.fn("complex_add", 2, "(a: Math.Complex, b: Math.Complex)", named::complex(),
                 {named::complex(), named::complex()}),
            m.fn("complex_argument", 1, "(c: Math.Complex)", R::number_type(), {named::complex()}),
            m.fn("complex_conjugate", 1, "(c: Math.Complex)", named::complex(), {named::complex()}),
            m.fn("complex_divide", 2, "(a: Math.Complex, b: Math.Complex)",
                 R::result(named::complex()), {named::complex(), named::complex()}),
            m.fn("complex_from_polar", 1, "(p: Math.Polar)", named::complex(), {named::polar()}),
            m.fn("complex_magnitude", 1, "(c: Math.Complex)", R::number_type(), {named::complex()}),
            m.fn("complex_multiply", 2, "(a: Math.Complex, b: Math.Complex)", named::complex(),
                 {named::complex(), named::complex()}),
            m.fn("complex_subtract", 2, "(a: Math.Complex, b: Math.Complex)", named::complex(),
                 {named::complex(), named::complex()}),
            m.fn("complex_to_polar", 1, "(c: Math.Complex)", named::polar(), {named::complex()}),
            m.fn("clamp", 3, "(value: number, min: number, max: number)", R::result_number(),
                 {p.number, p.number, p.number}),
            m.fn("cosine", 1, "(angle: number)", R::result_number(), {p.number}),
            m.fn("degrees", 1, "(radians: number)", R::number_type(), {p.number}),
            m.fn("digit_count", 1, "(value: integer)", R::integer_type(), {p.integer}),
            m.fn("digit_sum", 1, "(value: integer)", R::integer_type(), {p.integer}),
            m.constant("e", R::number_type()),
            m.constant("epsilon", R::number_type()),
            m.fn("erf", 1, "(x: number)", R::number_type(), {p.number}),
            m.fn("exponential", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("factorial", 1, "(value: integer)", R::result_integer(), {p.integer}),
            m.fn("floor", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("fraction", 2, "(numerator: integer, denominator: integer)",
                 R::result(named::fraction()), {p.integer, p.integer}),
            m.fn("fraction_add", 2, "(a: Math.Fraction, b: Math.Fraction)", named::fraction(),
                 {named::fraction(), named::fraction()}),
            m.fn("fraction_compare", 2, "(a: Math.Fraction, b: Math.Fraction)", named::ordering(),
                 {named::fraction(), named::fraction()}),
            m.fn("fraction_divide", 2, "(a: Math.Fraction, b: Math.Fraction)",
                 R::result(named::fraction()), {named::fraction(), named::fraction()}),
            m.fn("fraction_multiply", 2, "(a: Math.Fraction, b: Math.Fraction)", named::fraction(),
                 {named::fraction(), named::fraction()}),
            m.fn("fraction_subtract", 2, "(a: Math.Fraction, b: Math.Fraction)", named::fraction(),
                 {named::fraction(), named::fraction()}),
            m.fn("fraction_to_number", 1, "(f: Math.Fraction)", R::number_type(),
                 {named::fraction()}),
            m.fn("from_polar", 1, "(p: Math.Polar)", named::vector2(), {named::polar()}),
            m.fn("gamma", 1, "(x: number)", R::result_number(), {p.number}),
            m.fn("greatest_common_divisor", 2, "(a: integer, b: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.constant("infinity", R::number_type()),
            m.fn("is_infinite", 1, "(value: number)", R::boolean_type(), {p.number}),
            m.fn("is_finite", 1, "(value: number)", R::boolean_type(), {p.number}),
            m.fn("is_even", 1, "(value: integer)", R::boolean_type(), {p.integer}),
            m.fn("is_not_a_number", 1, "(value: number)", R::boolean_type(), {p.number}),
            m.fn("is_odd", 1, "(value: integer)", R::boolean_type(), {p.integer}),
            m.fn("is_prime", 1, "(value: integer)", R::boolean_type(), {p.integer}),
            m.fn("least_common_multiple", 2, "(a: integer, b: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("lerp", 3, "(a: number, b: number, t: number)", R::result_number(),
                 {p.number, p.number, p.number}),
            m.fn("log_10", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("log_2", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("log_base", 2, "(value: number, base: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("log_e", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("max", 2, "(a: number, b: number)", R::number_type(), {p.number, p.number}),
            m.constant("max_integer", R::integer_type()),
            m.constant("max_number", R::number_type()),
            m.fn("min", 2, "(a: number, b: number)", R::number_type(), {p.number, p.number}),
            m.constant("min_integer", R::integer_type()),
            m.constant("min_number", R::number_type()),
            m.constant("nan", R::number_type()),
            m.fn("normalize_angle", 1, "(radians: number)", R::number_type(), {p.number}),
            m.fn("nth_root", 2, "(value: number, n: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("permutations", 2, "(n: integer, k: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.constant("pi", R::number_type()),
            m.fn("power", 2, "(base: number, exponent: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("radians", 1, "(degrees: number)", R::number_type(), {p.number}),
            m.fn(
                "remap", 5,
                "(value: number, in_min: number, in_max: number, out_min: number, out_max: number)",
                R::result_number(), {p.number, p.number, p.number, p.number, p.number}),
            m.fn("remainder", 2, "(a: integer | number, b: integer | number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("round", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("round_to", 2, "(value: number, places: integer)", R::result_number(),
                 {p.number, p.integer}),
            m.fn("sign", 1, "(value: integer | number)", R::integer_type(), {p.number}),
            m.fn("sign_of", 1, "(value: integer | number)", named::sign(), {p.number}),
            m.fn("sin_of", 1, "(angle: Math.Angle)", R::number_type(), {named::angle()}),
            m.fn("sine", 1, "(angle: number)", R::result_number(), {p.number}),
            m.fn("sigmoid", 1, "(x: number)", R::number_type(), {p.number}),
            m.fn("smooth_step", 3, "(edge0: number, edge1: number, x: number)", R::result_number(),
                 {p.number, p.number, p.number}),
            m.fn("square_root", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("sum", 1, "(values: array<number>)", R::result_number(), {p.array_any}),
            m.fn("tangent", 1, "(angle: number)", R::result_number(), {p.number}),
            m.constant("tau", R::number_type()),
            m.fn("to_degrees", 1, "(angle: Math.Angle)", R::number_type(), {named::angle()}),
            m.fn("to_polar", 1, "(v: Math.Vector2)", named::polar(), {named::vector2()}),
            m.fn("to_radians", 1, "(angle: Math.Angle)", R::number_type(), {named::angle()}),
            m.fn("truncate", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("vec2_add", 2, "(a: Math.Vector2, b: Math.Vector2)", named::vector2(),
                 {named::vector2(), named::vector2()}),
            m.fn("vec2_dot", 2, "(a: Math.Vector2, b: Math.Vector2)", R::number_type(),
                 {named::vector2(), named::vector2()}),
            m.fn("vec2_length", 1, "(v: Math.Vector2)", R::number_type(), {named::vector2()}),
            m.fn("vec2_normalize", 1, "(v: Math.Vector2)", named::vector2(), {named::vector2()}),
            m.fn("vec2_scale", 2, "(v: Math.Vector2, s: number)", named::vector2(),
                 {named::vector2(), p.number}),
            m.fn("vec2_sub", 2, "(a: Math.Vector2, b: Math.Vector2)", named::vector2(),
                 {named::vector2(), named::vector2()}),
            m.fn("vec3_add", 2, "(a: Math.Vector3, b: Math.Vector3)", named::vector3(),
                 {named::vector3(), named::vector3()}),
            m.fn("vec3_cross", 2, "(a: Math.Vector3, b: Math.Vector3)", named::vector3(),
                 {named::vector3(), named::vector3()}),
            m.fn("vec3_dot", 2, "(a: Math.Vector3, b: Math.Vector3)", R::number_type(),
                 {named::vector3(), named::vector3()}),
            m.fn("vec3_length", 1, "(v: Math.Vector3)", R::number_type(), {named::vector3()}),
            m.fn("vec3_normalize", 1, "(v: Math.Vector3)", named::vector3(), {named::vector3()}),
            m.fn("vec3_scale", 2, "(v: Math.Vector3, s: number)", named::vector3(),
                 {named::vector3(), p.number}),
            m.fn("vec3_sub", 2, "(a: Math.Vector3, b: Math.Vector3)", named::vector3(),
                 {named::vector3(), named::vector3()}),
            m.fn("vec4_add", 2, "(a: Math.Vector4, b: Math.Vector4)", named::vector4(),
                 {named::vector4(), named::vector4()}),
            m.fn("vec4_dot", 2, "(a: Math.Vector4, b: Math.Vector4)", R::number_type(),
                 {named::vector4(), named::vector4()}),
            m.fn("vec4_length", 1, "(v: Math.Vector4)", R::number_type(), {named::vector4()}),
            m.fn("vec4_normalize", 1, "(v: Math.Vector4)", named::vector4(), {named::vector4()}),
            m.fn("vec4_scale", 2, "(v: Math.Vector4, s: number)", named::vector4(),
                 {named::vector4(), p.number}),
            m.fn("vec4_sub", 2, "(a: Math.Vector4, b: Math.Vector4)", named::vector4(),
                 {named::vector4(), named::vector4()}),
            m.fn("vector2", 2, "(x: number, y: number)", named::vector2(), {p.number, p.number}),
            m.fn("vector3", 3, "(x: number, y: number, z: number)", named::vector3(),
                 {p.number, p.number, p.number}),
            m.fn("vector4", 4, "(x: number, y: number, z: number, w: number)", named::vector4(),
                 {p.number, p.number, p.number, p.number}),
            m.fn("interval", 2, "(min: number, max: number)", R::result(named::interval()),
                 {p.number, p.number}),
            m.fn("interval_contains", 2, "(iv: Math.Interval, x: number)", R::boolean_type(),
                 {named::interval(), p.number}),
            m.fn("interval_clamp", 2, "(iv: Math.Interval, x: number)", R::number_type(),
                 {named::interval(), p.number}),
            m.fn("interval_length", 1, "(iv: Math.Interval)", R::number_type(),
                 {named::interval()}),
            m.fn("intervals_overlap", 2, "(a: Math.Interval, b: Math.Interval)", R::boolean_type(),
                 {named::interval(), named::interval()}),
            m.fn("rect", 4, "(x: number, y: number, width: number, height: number)", named::rect(),
                 {p.number, p.number, p.number, p.number}),
            m.fn("rect_contains", 3, "(r: Math.Rect, x: number, y: number)", R::boolean_type(),
                 {named::rect(), p.number, p.number}),
            m.fn("rect_intersects", 2, "(a: Math.Rect, b: Math.Rect)", R::boolean_type(),
                 {named::rect(), named::rect()}),
            m.fn("rect_intersection", 2, "(a: Math.Rect, b: Math.Rect)", R::optional(named::rect()),
                 {named::rect(), named::rect()}),
            m.fn("rect_union", 2, "(a: Math.Rect, b: Math.Rect)", named::rect(),
                 {named::rect(), named::rect()}),
            m.fn("rect_center", 1, "(r: Math.Rect)", named::vector2(), {named::rect()}),
            m.fn("rect_area", 1, "(r: Math.Rect)", R::number_type(), {named::rect()}),
            m.fn("circle", 2, "(center: Math.Vector2, radius: number)", named::circle(),
                 {named::vector2(), p.number}),
            m.fn("circle_contains", 2, "(c: Math.Circle, point: Math.Vector2)", R::boolean_type(),
                 {named::circle(), named::vector2()}),
            m.fn("circle_intersects", 2, "(a: Math.Circle, b: Math.Circle)", R::boolean_type(),
                 {named::circle(), named::circle()}),
            m.fn("circle_rect_intersects", 2, "(c: Math.Circle, r: Math.Rect)", R::boolean_type(),
                 {named::circle(), named::rect()}),
            m.fn("matrix2", 4, "(m00: number, m01: number, m10: number, m11: number)",
                 named::matrix2(), {p.number, p.number, p.number, p.number}),
            m.fn("matrix3", 9,
                 "(m00: number, m01: number, m02: number, m10: number, m11: number, "
                 "m12: number, m20: number, m21: number, m22: number)",
                 named::matrix3(),
                 {p.number, p.number, p.number, p.number, p.number, p.number, p.number, p.number,
                  p.number}),
            m.fn("mat2_identity", 0, "()", named::matrix2()),
            m.fn("mat3_identity", 0, "()", named::matrix3()),
            m.fn("mat2_multiply", 2, "(a: Math.Matrix2, b: Math.Matrix2)", named::matrix2(),
                 {named::matrix2(), named::matrix2()}),
            m.fn("mat3_multiply", 2, "(a: Math.Matrix3, b: Math.Matrix3)", named::matrix3(),
                 {named::matrix3(), named::matrix3()}),
            m.fn("mat2_determinant", 1, "(m: Math.Matrix2)", R::number_type(), {named::matrix2()}),
            m.fn("mat3_determinant", 1, "(m: Math.Matrix3)", R::number_type(), {named::matrix3()}),
            m.fn("mat2_transform", 2, "(m: Math.Matrix2, v: Math.Vector2)", named::vector2(),
                 {named::matrix2(), named::vector2()}),
            m.fn("mat3_transform", 2, "(m: Math.Matrix3, v: Math.Vector3)", named::vector3(),
                 {named::matrix3(), named::vector3()}),
            m.fn("matrix4", 16,
                 "(m00: number, m01: number, m02: number, m03: number, m10: number, m11: number, "
                 "m12: number, m13: number, m20: number, m21: number, m22: number, m23: number, "
                 "m30: number, m31: number, m32: number, m33: number)",
                 named::matrix4(),
                 {p.number, p.number, p.number, p.number, p.number, p.number, p.number, p.number,
                  p.number, p.number, p.number, p.number, p.number, p.number, p.number, p.number}),
            m.fn("mat4_identity", 0, "()", named::matrix4()),
            m.fn("mat4_multiply", 2, "(a: Math.Matrix4, b: Math.Matrix4)", named::matrix4(),
                 {named::matrix4(), named::matrix4()}),
            m.fn("mat4_determinant", 1, "(m: Math.Matrix4)", R::number_type(), {named::matrix4()}),
            m.fn("mat4_transform", 2, "(m: Math.Matrix4, v: Math.Vector4)", named::vector4(),
                 {named::matrix4(), named::vector4()}),
            m.fn("atan2", 2, "(y: number, x: number)", R::result_number(), {p.number, p.number}),
            m.fn("hypot", 2, "(x: number, y: number)", R::number_type(), {p.number, p.number}),
            m.fn("log", 2, "(base: number, value: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("cube_root", 1, "(value: number)", R::number_type(), {p.number}),
            m.fn("hyperbolic_sine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("hyperbolic_cosine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("hyperbolic_tangent", 1, "(value: number)", R::number_type(), {p.number}),
            m.fn("wrap", 3, "(x: number, lo: number, hi: number)", R::number_type(),
                 {p.number, p.number, p.number}),
        });
}

void register_converter_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                  const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("character_to_codepoint", 1, "(char: string)", R::result_integer(), {p.string}),
            m.fn("codepoint_to_character", 1, "(code: integer)", R::result_string(), {p.integer}),
            m.fn("from_binary", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("from_hexadecimal", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("from_octal", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("from_roman", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("number_to_words", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("ordinal", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_binary", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_boolean", 1, "(value: string)", R::result_boolean(), {p.string}),
            m.fn("to_hexadecimal", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_octal", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_integer", 1, "(value: string | number)", R::result_integer(), {p.any}),
            m.fn("to_number", 1, "(value: string | integer)", R::result_number(), {p.any}),
            m.fn("to_roman", 1, "(value: integer)", R::result_string(), {p.integer}),
            m.fn("to_string", 1, "(value: T)", R::string_type(), {p.any}),
        });
}

void register_random_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                               const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("choice", 1, "(arr: array<T>)", R::result_any(), {p.any}),
            m.fn("generate_boolean", 0, "()", R::boolean_type(), {}),
            m.fn("generate_bytes", 1, "(n: integer)", R::result(R::array(R::integer_type())),
                 {p.integer}),
            m.fn("generate_integer", 2, "(min: integer, max: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("generate_number", 0, "()", R::number_type(), {}),
            m.fn("generate_string", 1, "(length: integer)", R::result_string(), {p.integer}),
            m.fn("sample", 2, "(arr: array<T>, count: integer)", R::result_array_any(),
                 {p.any, p.integer}),
            m.fn("sample_from", 1, "(distribution: Random.Distribution)", R::result_number(),
                 {named::random_distribution()}),
            m.fn("set_seed", 1, "(seed: integer)", R::void_type(), {p.integer}),
            m.fn("shuffle", 1, "(arr: array<T>)", R::array_any(), {p.any}),
            m.fn("generate_uuid", 0, "()", R::string_type(), {}),
            m.fn("parse_uuid", 1, "(uuid: string)", R::result(named::uuid()), {p.string}),
            m.fn("secure_boolean", 0, "()", R::result_boolean(), {}),
            m.fn("secure_bytes", 1, "(n: integer)", R::result(R::array(R::integer_type())),
                 {p.integer}),
            m.fn("secure_integer", 2, "(min: integer, max: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("secure_number", 0, "()", R::result_number(), {}),
            m.fn("secure_string", 1, "(length: integer)", R::result_string(), {p.integer}),
            m.fn("secure_uuid", 0, "()", R::result_string(), {}),
            m.fn("uuid_typed", 0, "()", named::uuid(), {}),
            m.fn("uuid_to_string", 1, "(uuid: Random.Uuid)", R::string_type(), {named::uuid()}),
        });
}

} // namespace luma::stdlib::detail
