#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_graphical_ui_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                     const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.variadic_fn("above", 2, "(child: widget, overlay: widget, style?: dictionary)",
                          named::widget(), {p.widget, p.widget}),
            m.fn("accessible", 2, "(child: widget, attributes: dictionary)", named::widget(),
                 {p.widget, p.dict_any}),
            m.variadic_fn("accordion", 1, "(sections: array<dictionary>)", named::widget(),
                          {p.array_any}),
            m.variadic_fn("alert", 1, "(message: string, severity?: string, style?: dictionary)",
                          named::widget(), {p.string}),
            m.variadic_fn("alert_of", 2,
                          "(message: string, severity: GraphicalUi.Severity, style?: dictionary)",
                          named::widget(), {p.string, named::gui_severity()}),
            m.fn("align_bottom", 0, "()", named::widget()),
            m.fn("align_left", 0, "()", named::widget()),
            m.fn("align_right", 0, "()", named::widget()),
            m.fn("align_top", 0, "()", named::widget()),
            m.variadic_fn("animate", 2,
                          "(child: widget, keyframes: array<dictionary>, options?: dictionary)",
                          named::widget(), {p.widget, p.array_any}),
            m.fn("announce", 1, "(text: string)", named::widget(), {p.string}),
            m.fn("app", 1, "(config: dictionary)", R::void_type(), {p.dict_any}),
            m.variadic_fn("area_chart", 2,
                          "(labels: array<string>, values: array<number>, style?: dictionary)",
                          named::widget(), {p.array_string, p.array_number}),
            m.fn("aria_describedby", 2, "(desc_id: string, child: widget)", named::widget(),
                 {p.string, p.widget}),
            m.fn("aria_live", 2, "(level: string, child: widget)", named::widget(),
                 {p.string, p.widget}),
            m.variadic_fn("avatar", 1, "(name: string, url?: string)", named::widget(), {p.string}),
            m.variadic_fn("badge", 1, "(text: string)", named::widget(), {p.string}),
            m.fn("batch", 1, "(commands: array<command>)", named::widget(), {p.array_any}),
            m.variadic_fn("behind", 2, "(child: widget, overlay: widget, style?: dictionary)",
                          named::widget(), {p.widget, p.widget}),
            m.variadic_fn("below", 2, "(child: widget, overlay: widget, style?: dictionary)",
                          named::widget(), {p.widget, p.widget}),
            m.fn("blur", 1, "(widget_id: string)", named::widget(), {p.string}),
            m.variadic_fn("breadcrumb", 1,
                          "(items: array<string>, on_navigate?: func(string) -> any)",
                          named::widget(), {p.array_string}),
            m.variadic_fn("button", 2,
                          "(label: string, on_click: func() -> any, style?: dictionary)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn("button_of", 3,
                          "(label: string, on_click: func() -> any, "
                          "variant: GraphicalUi.ButtonVariant, style?: dictionary)",
                          named::widget(), {p.string, p.func, named::gui_button_variant()}),
            m.fn("button_variant_to_string", 1, "(variant: GraphicalUi.ButtonVariant)",
                 R::string_type(), {named::gui_button_variant()}),
            m.variadic_fn("card", 1, "(children: array<widget>)", named::widget(), {p.array_any}),
            m.fn("center", 0, "()", named::widget()),
            m.fn("center_x", 0, "()", named::widget()),
            m.fn("center_y", 0, "()", named::widget()),
            m.variadic_fn("checkbox", 3,
                          "(label: string, checked: boolean, on_toggle: func(boolean) -> any, "
                          "style?: dictionary)",
                          named::widget(), {p.string, p.boolean, p.func}),
            m.fn("classify_device", 2, "(width: integer, height: integer)", named::widget(),
                 {p.integer, p.integer}),
            m.fn("classify_device_typed", 2, "(width: integer, height: integer)",
                 named::gui_device_info(), {p.integer, p.integer}),
            m.fn("clear_local_storage", 0, "()", named::widget()),
            m.variadic_fn("column", 1, "(children: array<widget>, style?: dictionary)",
                          named::widget(), {p.array_any}),
            m.variadic_fn("color_picker", 2, "(value: string, on_change: func(string) -> any)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn("combobox", 3,
                          "(value: string, options: array<string>, on_change: func(string) -> "
                          "any, on_select?: func(string) -> any)",
                          named::widget(), {p.string, p.array_string, p.func}),
            m.fn("component", 3, "(id: string, model_slice: any, render_fn: func(any) -> widget)",
                 named::widget(), {p.string, p.any, p.func}),
            m.variadic_fn("confirm", 3,
                          "(title: string, message: string, on_confirm: func() -> any, on_cancel?: "
                          "func() -> any, options?: dictionary)",
                          named::widget(), {p.string, p.string, p.func}),
            m.fn("constrained_fill", 2, "(min: integer, max: integer)", named::widget(),
                 {p.integer, p.integer}),
            m.fn("debounce", 3,
                 "(id: string, milliseconds: integer, callback: func(result<string>) -> any)",
                 named::widget(), {p.string, p.integer, p.func}),
            m.variadic_fn("debug", 1, "(child: widget, style?: dictionary)", named::widget(),
                          {p.widget}),
            m.variadic_fn("date_picker", 2, "(value: string, on_change: func(string) -> any)",
                          named::widget(), {p.string, p.func}),
            m.fn("delay", 2, "(milliseconds: integer, on_done: func(result<string>) -> any)",
                 named::widget(), {p.integer, p.func}),
            m.variadic_fn("dialog", 3,
                          "(title: string, children: array<widget>, is_open: boolean, on_close?: "
                          "func() -> any, style?: dictionary)",
                          named::widget(), {p.string, p.array_any, p.boolean}),
            m.variadic_fn("donut_chart", 2,
                          "(labels: array<string>, values: array<number>, center_label?: string, "
                          "style?: dictionary)",
                          named::widget(), {p.array_string, p.array_number}),
            m.variadic_fn("draggable", 2, "(child: widget, data: string)", named::widget(),
                          {p.widget, p.string}),
            m.variadic_fn("drop_target", 2, "(child: widget, on_drop: func(string) -> any)",
                          named::widget(), {p.widget, p.func}),
            m.variadic_fn("drop_target_typed", 2,
                          "(child: widget, on_drop: func(GraphicalUi.DropEvent) -> any)",
                          named::widget(), {p.widget, p.func}),
            m.variadic_fn("dropdown", 3,
                          "(options: array<string>, value: string, on_select: func(string) -> any, "
                          "style?: dictionary)",
                          named::widget(), {p.array_string, p.string, p.func}),
            m.fn("download_file", 2, "(url: string, filename: string)", named::widget(),
                 {p.string, p.string}),
            m.variadic_fn("empty_state", 1, "(message: string, options?: dictionary)",
                          named::widget(), {p.string}),
            m.fn("error_boundary", 2,
                 "(fallback_fn: func(string) -> widget, view_fn: func() -> widget)",
                 named::widget(), {p.func, p.func}),
            m.variadic_fn("field", 2, "(label: string, control: widget, options?: dictionary)",
                          named::widget(), {p.string, p.widget}),
            m.variadic_fn("field_error", 1, "(message: string)", named::widget(), {p.string}),
            m.fn("fill", 0, "()", R::string_type()),
            m.fn("fill_portion", 1, "(n: integer)", R::string_type(), {p.integer}),
            m.variadic_fn("file_input", 1, "(on_select: func(string) -> any, accept?: string)",
                          named::widget(), {p.func}),
            m.variadic_fn("flexible_space", 0, "(style?: dictionary)", named::widget()),
            m.fn("focus", 1, "(widget_id: string)", named::widget(), {p.string}),
            m.variadic_fn("font_face", 2, "(path: string, family: string, options?: dictionary)",
                          named::widget(), {p.string, p.string}),
            m.variadic_fn("form", 2, "(children: array<widget>, on_submit: func() -> any)",
                          named::widget(), {p.array_any, p.func}),
            m.variadic_fn("grid", 2,
                          "(columns: integer, children: array<widget>, style?: dictionary)",
                          named::widget(), {p.integer, p.array_any}),
            m.fn("get_local_storage", 2, "(key: string, on_result: func(string) -> any)",
                 named::widget(), {p.string, p.func}),
            m.variadic_fn("heading", 1, "(text: string, level?: integer, style?: dictionary)",
                          named::widget(), {p.string}),
            m.variadic_fn("horizontal_bar_chart", 2,
                          "(labels: array<string>, values: array<number>, style?: dictionary)",
                          named::widget(), {p.array_string, p.array_number}),
            m.variadic_fn("horizontal_spacer", 0, "(width?: integer)", named::widget()),
            m.variadic_fn("http_delete", 2,
                          "(url: string, on_result: func(result<string>) -> any, headers?: "
                          "dictionary, timeout?: integer)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn("http_get", 2,
                          "(url: string, on_result: func(result<string>) -> any, headers?: "
                          "dictionary, timeout?: integer)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn("http_get_full", 2,
                          "(url: string, on_result: func(result<GraphicalUi.HttpResponse>) -> any, "
                          "headers?: dictionary, timeout?: integer)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn("http_patch", 3,
                          "(url: string, body: string, on_result: func(result<string>) -> any, "
                          "headers?: dictionary, timeout?: integer)",
                          named::widget(), {p.string, p.string, p.func}),
            m.variadic_fn(
                "http_post", 3,
                "(url: string, body: string, on_result: func(result<string>) -> any, headers?: "
                "dictionary, timeout?: integer)",
                named::widget(), {p.string, p.string, p.func}),
            m.variadic_fn(
                "http_post_full", 3,
                "(url: string, body: string, on_result: func(result<GraphicalUi.HttpResponse>) -> "
                "any, headers?: dictionary, timeout?: integer)",
                named::widget(), {p.string, p.string, p.func}),
            m.variadic_fn("http_put", 3,
                          "(url: string, body: string, on_result: func(result<string>) -> any, "
                          "headers?: dictionary, timeout?: integer)",
                          named::widget(), {p.string, p.string, p.func}),
            m.variadic_fn("icon", 1, "(name: string, size?: integer, style?: dictionary)",
                          named::widget(), {p.string}),
            m.fn("if_dark", 2, "(dark_value: string, light_value: string)", named::widget(),
                 {p.string, p.string}),
            m.variadic_fn("image", 1, "(source: string, style?: dictionary)", named::widget(),
                          {p.string}),
            m.variadic_fn("in_front", 2, "(child: widget, overlay: widget, style?: dictionary)",
                          named::widget(), {p.widget, p.widget}),
            m.variadic_fn("infinite_scroll", 3,
                          "(items: array, item_height: integer, on_load_more: func() -> any)",
                          named::widget(), {p.array_any, p.integer, p.func}),
            m.fn("inspect", 1, "(child: widget)", named::widget(), {p.widget}),
            m.fn("keyed", 2, "(key: string, child: widget)", named::widget(), {p.string, p.any}),
            m.variadic_fn("label", 1, "(text: string, style?: dictionary)", named::widget(),
                          {p.string}),
            m.variadic_fn("line_chart", 2,
                          "(labels: array<string>, values: array<number>, style?: dictionary)",
                          named::widget(), {p.array_string, p.array_number}),
            m.variadic_fn("link", 2, "(text: string, on_click_or_url: any, style?: dictionary)",
                          named::widget(), {p.string, p.any}),
            m.variadic_fn(
                "list", 1,
                "(items: array<any>, on_select?: func(integer) -> any, style?: dictionary)",
                named::widget(), {p.array_any}),
            m.fn("load_stylesheet", 1, "(path: string)", named::widget(), {p.string}),
            m.variadic_fn("menu", 3,
                          "(label: string, items: array<string>, on_select: func(string) -> any)",
                          named::widget(), {p.string, p.array_string, p.func}),
            m.variadic_fn("merge_styles", 2, "(base: dictionary, overrides: dictionary, ...)",
                          named::widget(), {p.dict_any, p.dict_any}),
            m.fn("navigate", 1, "(route: string)", named::widget(), {p.string}),
            m.fn("navigate_back", 0, "()", named::widget()),
            m.variadic_fn("navigation_link", 2, "(text: string, message: any, style?: dictionary)",
                          named::widget(), {p.string, p.any}),
            m.fn("none", 0, "()", named::widget()),
            m.variadic_fn("notify", 1, "(title: string, body?: string, icon?: string)",
                          named::widget(), {p.string}),
            m.variadic_fn(
                "number_input", 4,
                "(value: number, min: number, max: number, on_change: func(number) -> any)",
                named::widget(), {p.number, p.number, p.number, p.func}),
            m.fn("on_animation_frame", 2, "(id: string, on_frame: func() -> any)", named::widget(),
                 {p.string, p.func}),
            m.fn("on_drag", 3, "(id: string, event_type: string, on_drag: func(dictionary) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.fn("on_drag_typed", 2, "(id: string, on_drag: func(GraphicalUi.DragEvent) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("on_focus", 2, "(id: string, on_focus: func(boolean) -> any)", named::widget(),
                 {p.string, p.func}),
            m.fn("on_idle", 3, "(id: string, timeout_ms: integer, on_idle: func() -> any)",
                 named::widget(), {p.string, p.integer, p.func}),
            m.fn("on_key", 3, "(id: string, key_filter: string, on_key: func(string) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.fn("on_key_typed", 3,
                 "(id: string, key_filter: string, on_key: func(GraphicalUi.KeyEvent) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.variadic_fn("on_left", 2, "(child: widget, overlay: widget, style?: dictionary)",
                          named::widget(), {p.widget, p.widget}),
            m.fn("on_media_query", 3, "(id: string, query: string, on_match: func(boolean) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.fn("on_mouse", 3,
                 "(id: string, event_type: string, on_event: func(dictionary) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.fn("on_mouse_typed", 3,
                 "(id: string, event_type: string, on_event: func(GraphicalUi.MouseEvent) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.variadic_fn("on_mouse_of", 3,
                          "(id: string, event_type: GraphicalUi.MouseEventType, on_event: "
                          "func(dictionary) -> any, throttle_ms?: integer)",
                          named::widget(), {p.string, named::gui_mouse_event_type(), p.func}),
            m.fn("on_offline", 2, "(id: string, on_offline: func() -> any)", named::widget(),
                 {p.string, p.func}),
            m.fn("on_online", 2, "(id: string, on_online: func() -> any)", named::widget(),
                 {p.string, p.func}),
            m.fn("on_resize", 2, "(id: string, on_resize: func(integer, integer) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("on_resize_typed", 2,
                 "(id: string, on_resize: func(GraphicalUi.WindowSize) -> any)", named::widget(),
                 {p.string, p.func}),
            m.variadic_fn("on_right", 2, "(child: widget, overlay: widget, style?: dictionary)",
                          named::widget(), {p.widget, p.widget}),
            m.fn("on_scroll", 2, "(id: string, on_scroll: func(dictionary) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("on_scroll_typed", 2,
                 "(id: string, on_scroll: func(GraphicalUi.ScrollPosition) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("on_storage_change", 3,
                 "(id: string, key: string, on_change: func(string) -> any)", named::widget(),
                 {p.string, p.string, p.func}),
            m.fn("on_storage_change_typed", 3,
                 "(id: string, key: string, on_change: func(GraphicalUi.StorageEvent) -> any)",
                 named::widget(), {p.string, p.string, p.func}),
            m.fn("on_tick", 3, "(id: string, interval_ms: integer, on_tick: func() -> any)",
                 named::widget(), {p.string, p.integer, p.func}),
            m.fn("on_visibility_change", 2, "(id: string, on_change: func(boolean) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("on_visibility_change_typed", 2,
                 "(id: string, on_change: func(GraphicalUi.VisibilityState) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("on_wheel_typed", 2, "(id: string, on_wheel: func(GraphicalUi.WheelDelta) -> any)",
                 named::widget(), {p.string, p.func}),
            m.fn("open_url", 1, "(url: string)", named::widget(), {p.string}),
            m.fn("padding", 1, "(pixels: integer)", named::widget(), {p.integer}),
            m.fn("padding_xy", 2, "(x: integer, y: integer)", named::widget(),
                 {p.integer, p.integer}),
            m.variadic_fn("paginator", 3,
                          "(current_page: integer, total_pages: integer, on_page_change: "
                          "func(integer) -> any)",
                          named::widget(), {p.integer, p.integer, p.func}),
            m.variadic_fn("panel", 2,
                          "(title: string, children: array<widget>, style?: dictionary)",
                          named::widget(), {p.string, p.array_any}),
            m.variadic_fn("pie_chart", 2,
                          "(labels: array<string>, values: array<number>, style?: dictionary)",
                          named::widget(), {p.array_string, p.array_number}),
            m.variadic_fn("popover", 2, "(label: string, content: widget)", named::widget(),
                          {p.string, p.widget}),
            m.fn("print", 0, "()", named::widget()),
            m.variadic_fn("progress", 2, "(value: number, max: number, style?: dictionary)",
                          named::widget(), {p.number, p.number}),
            m.variadic_fn("progress_bar", 2, "(value: number, max: number, style?: dictionary)",
                          named::widget(), {p.number, p.number}),
            m.fn("px", 1, "(n: integer)", R::string_type(), {p.integer}),
            m.variadic_fn("radio_group", 3,
                          "(options: array<string>, selected: string, on_select: func(string) -> "
                          "any, style?: dictionary)",
                          named::widget(), {p.array_string, p.string, p.func}),
            m.fn("random", 3, "(min: number, max: number, on_result: func(number) -> any)",
                 named::widget(), {p.number, p.number, p.func}),
            m.fn("read_clipboard", 1, "(on_result: func(result<string>) -> any)", named::widget(),
                 {p.func}),
            m.fn("redo", 2, "(model: any, redo_history: array)", named::widget(),
                 {p.any, p.array_any}),
            m.fn("remove_local_storage", 1, "(key: string)", named::widget(), {p.string}),
            m.fn("responsive", 1, "(breakpoints: dictionary)", named::widget(), {p.dict_any}),
            m.fn("router", 2, "(route: string, routes: dictionary)", named::widget(),
                 {p.string, p.dict_any}),
            m.variadic_fn("row", 1, "(children: array<widget>, style?: dictionary)",
                          named::widget(), {p.array_any}),
            m.variadic_fn("scatter_plot", 2,
                          "(x_values: array<number>, y_values: array<number>, x_label?: string, "
                          "y_label?: string, style?: dictionary)",
                          named::widget(), {p.array_number, p.array_number}),
            m.variadic_fn("scroll_column", 1, "(children: array<widget>, style?: dictionary)",
                          named::widget(), {p.array_any}),
            m.variadic_fn("scroll_row", 1, "(children: array<widget>, style?: dictionary)",
                          named::widget(), {p.array_any}),
            m.variadic_fn("scroll_to", 1, "(widget_id: string, behavior?: string)", named::widget(),
                          {p.string}),
            m.fn("scroll_to_of", 2, "(widget_id: string, behavior: GraphicalUi.ScrollBehavior)",
                 named::widget(), {p.string, named::gui_scroll_behavior()}),
            m.variadic_fn(
                "search_input", 2,
                "(value: string, on_change: func(string) -> any, on_clear?: func() -> any)",
                named::widget(), {p.string, p.func}),
            m.variadic_fn("separator", 0, "(style?: dictionary)", named::widget()),
            m.fn("set_local_storage", 2, "(key: string, value: string)", named::widget(),
                 {p.string, p.string}),
            m.fn("set_theme_mode", 1, "(mode: string)", named::widget(), {p.string}),
            m.fn("set_theme_mode_of", 1, "(mode: GraphicalUi.ThemeMode)", named::widget(),
                 {named::gui_theme_mode()}),
            m.fn("theme_mode_to_string", 1, "(mode: GraphicalUi.ThemeMode)", R::string_type(),
                 {named::gui_theme_mode()}),
            m.fn("set_title", 1, "(title: string)", named::widget(), {p.string}),
            m.fn("severity_to_string", 1, "(severity: GraphicalUi.Severity)", R::string_type(),
                 {named::gui_severity()}),
            m.fn("mouse_event_type_to_string", 1, "(event_type: GraphicalUi.MouseEventType)",
                 R::string_type(), {named::gui_mouse_event_type()}),
            m.fn("shrink", 0, "()", R::string_type()),
            m.variadic_fn("skeleton", 0, "(width?: integer, height?: integer)", named::widget()),
            m.variadic_fn(
                "slider",
                4,
                "(value: number, min: number, max: number, on_change: func(number) -> any, style?: "
                "dictionary)",
                named::widget(), {p.number, p.number, p.number, p.func}),
            m.fn("sort_direction_to_string", 1, "(direction: GraphicalUi.SortDirection)",
                 R::string_type(), {named::gui_sort_direction()}),
            m.fn("visibility_state_to_string", 1, "(state: GraphicalUi.VisibilityState)",
                 R::string_type(), {named::gui_visibility_state()}),
            m.fn("space_around", 0, "()", named::widget()),
            m.fn("space_between", 0, "()", named::widget()),
            m.fn("space_evenly", 0, "()", named::widget()),
            m.variadic_fn("spacer", 0, "(height?: integer, style?: dictionary)", named::widget()),
            m.fn("spacing", 1, "(pixels: integer)", named::widget(), {p.integer}),
            m.fn("spacing_xy", 2, "(x: integer, y: integer)", named::widget(),
                 {p.integer, p.integer}),
            m.variadic_fn("spinner", 0, "(label?: string, style?: dictionary)", named::widget()),
            m.fn("style", 1, "(properties: dictionary)", named::widget(), {p.dict_any}),
            m.fn("stylesheet", 1, "(css: string)", named::widget(), {p.string}),
            m.variadic_fn("switch", 3,
                          "(label: string, checked: boolean, on_toggle: func(boolean) -> any)",
                          named::widget(), {p.string, p.boolean, p.func}),
            m.variadic_fn("table", 2,
                          "(headers: array<string>, rows: array<array<any>>, on_row_click?: "
                          "func(integer) -> any, options?: dictionary)",
                          named::widget(), {p.array_string, p.array_any}),
            m.variadic_fn("tabs", 4,
                          "(labels: array<string>, active: integer, on_select: func(integer) -> "
                          "any, children: "
                          "array<widget>, style?: dictionary)",
                          named::widget(), {p.array_string, p.integer, p.func, p.array_any}),
            // Headless interaction-testing API (see graphicalui_testing.cpp).
            m.variadic_fn("test_click", 3,
                          "(config: dictionary, model: any, locator: string, index?: integer)",
                          R::any_type(), {p.dict_any, p.any, p.string}),
            m.fn("test_count", 3, "(config: dictionary, model: any, locator: string)",
                 R::integer_type(), {p.dict_any, p.any, p.string}),
            m.variadic_fn("test_event", 4,
                          "(config: dictionary, model: any, locator: string, event: string, "
                          "args?: array<any>, index?: integer)",
                          R::any_type(), {p.dict_any, p.any, p.string, p.string}),
            m.variadic_fn("test_find", 3,
                          "(config: dictionary, model: any, locator: string, index?: integer)",
                          R::dict(R::any_type()), {p.dict_any, p.any, p.string}),
            m.variadic_fn("test_drag", 3,
                          "(config: dictionary, model: any, phase: string, data?: string)",
                          R::any_type(), {p.dict_any, p.any, p.string}),
            m.variadic_fn("test_storage", 3,
                          "(config: dictionary, model: any, key: string, old_value?: "
                          "optional<string>, new_value?: optional<string>)",
                          R::any_type(), {p.dict_any, p.any, p.string}),
            m.fn("test_wheel", 4,
                 "(config: dictionary, model: any, delta_x: number, delta_y: number)",
                 R::any_type(), {p.dict_any, p.any, p.number, p.number}),
            m.fn("test_visibility", 3, "(config: dictionary, model: any, visible: boolean)",
                 R::any_type(), {p.dict_any, p.any, p.boolean}),
            m.fn("test_init", 1, "(config: dictionary)", R::any_type(), {p.dict_any}),
            m.variadic_fn(
                "test_input", 4,
                "(config: dictionary, model: any, locator: string, value: any, index?: integer)",
                R::any_type(), {p.dict_any, p.any, p.string, p.any}),
            m.fn("test_key", 3, "(config: dictionary, model: any, key: string)", R::any_type(),
                 {p.dict_any, p.any, p.string}),
            m.fn("test_message", 3, "(config: dictionary, model: any, message: any)", R::any_type(),
                 {p.dict_any, p.any, p.any}),
            m.fn("test_render", 2, "(config: dictionary, model: any)", R::dict(R::any_type()),
                 {p.dict_any, p.any}),
            m.variadic_fn("text_area", 2,
                          "(value: string, on_change: func(string) -> any, style?: dictionary)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn(
                "text_input", 2,
                "(value: string, on_change: func(string) -> any, placeholder?: string, style?: "
                "dictionary)",
                named::widget(), {p.string, p.func}),
            m.variadic_fn("time_picker", 2, "(value: string, on_change: func(string) -> any)",
                          named::widget(), {p.string, p.func}),
            m.variadic_fn("toast", 1,
                          "(message: string, severity?: string, duration?: integer, "
                          "action_label?: string, on_action?: func() -> any, style?: dictionary)",
                          named::widget(), {p.string}),
            m.variadic_fn("toast_of", 2,
                          "(message: string, severity: GraphicalUi.Severity, duration?: integer, "
                          "action_label?: string, on_action?: func() -> any, style?: dictionary)",
                          named::widget(), {p.string, named::gui_severity()}),
            m.variadic_fn("toast_region", 1, "(toasts: array<widget>, options?: dictionary)",
                          named::widget(), {p.array_any}),
            m.variadic_fn("toggle", 3,
                          "(label: string, checked: boolean, on_toggle: func(boolean) -> any, "
                          "style?: dictionary)",
                          named::widget(), {p.string, p.boolean, p.func}),
            m.variadic_fn("toolbar", 1, "(children: array<widget>, style?: dictionary)",
                          named::widget(), {p.array_any}),
            m.variadic_fn("tooltip", 2, "(text: string, child: widget, style?: dictionary)",
                          named::widget(), {p.string, p.widget}),
            m.variadic_fn("transition", 2, "(child: widget, properties: dictionary)",
                          named::widget(), {p.widget, p.dict_any}),
            m.fn("transition_preset", 1, "(name: string)", named::widget(), {p.string}),
            m.fn("undo", 2, "(model: any, undo_history: array)", named::widget(),
                 {p.any, p.array_any}),
            m.fn("validate_style", 1, "(style: dictionary)", R::result(named::widget()),
                 {p.dict_any}),
            m.variadic_fn("vertical_bar_chart", 2,
                          "(labels: array<string>, values: array<number>, style?: dictionary)",
                          named::widget(), {p.array_string, p.array_number}),
            m.fn("when", 2, "(condition: boolean, widget: widget)", named::widget(),
                 {p.boolean, p.any}),
            m.variadic_fn("wizard", 3,
                          "(steps: array<widget>, active_step: integer, on_step_change: "
                          "func(integer) -> any)",
                          named::widget(), {p.array_any, p.integer, p.func}),
            m.variadic_fn(
                "virtual_list", 3,
                "(items: array, item_height: integer, visible_count: integer, style?: dictionary)",
                named::widget(), {p.array_any, p.integer, p.integer}),
            m.fn("with_command", 2, "(model: any, command: dictionary)", named::widget(),
                 {p.any, p.dict_any}),
            m.variadic_fn("wrapped_row", 1, "(children: array<widget>, style?: dictionary)",
                          named::widget(), {p.array_any}),
            m.fn("write_clipboard", 1, "(text: string)", named::widget(), {p.string}),
            m.constant("DANGER", R::string_type()),
            m.constant("ERROR", R::string_type()),
            m.constant("GHOST", R::string_type()),
            m.constant("INFO", R::string_type()),
            m.constant("INIT", R::string_type()),
            m.constant("MODEL", R::string_type()),
            m.constant("PRIMARY", R::string_type()),
            m.constant("SECONDARY", R::string_type()),
            m.constant("SUBSCRIBE", R::string_type()),
            m.constant("SUCCESS", R::string_type()),
            m.constant("THEME", R::string_type()),
            m.constant("TITLE", R::string_type()),
            m.constant("UPDATE", R::string_type()),
            m.constant("VAR_BG", R::string_type()),
            m.constant("VAR_BORDER", R::string_type()),
            m.constant("VAR_DISABLED_BG", R::string_type()),
            m.constant("VAR_DISABLED_FG", R::string_type()),
            m.constant("VAR_ERROR", R::string_type()),
            m.constant("VAR_FG", R::string_type()),
            m.constant("VAR_FONT", R::string_type()),
            m.constant("VAR_GAP", R::string_type()),
            m.constant("VAR_INPUT_BG", R::string_type()),
            m.constant("VAR_INPUT_BORDER", R::string_type()),
            m.constant("VAR_INPUT_FOCUS", R::string_type()),
            m.constant("VAR_MEASURE", R::string_type()),
            m.constant("VAR_PRIMARY", R::string_type()),
            m.constant("VAR_PRIMARY_HOVER", R::string_type()),
            m.constant("VAR_RADIUS", R::string_type()),
            m.constant("VAR_RADIUS_FULL", R::string_type()),
            m.constant("VAR_RADIUS_LG", R::string_type()),
            m.constant("VAR_RADIUS_MD", R::string_type()),
            m.constant("VAR_RADIUS_NONE", R::string_type()),
            m.constant("VAR_RADIUS_SM", R::string_type()),
            m.constant("VAR_SHADOW", R::string_type()),
            m.constant("VAR_SHADOW_LG", R::string_type()),
            m.constant("VAR_SHADOW_MD", R::string_type()),
            m.constant("VAR_SHADOW_NONE", R::string_type()),
            m.constant("VAR_SHADOW_SM", R::string_type()),
            m.constant("VAR_SPACE_LG", R::string_type()),
            m.constant("VAR_SPACE_MD", R::string_type()),
            m.constant("VAR_SPACE_SM", R::string_type()),
            m.constant("VAR_SPACE_XL", R::string_type()),
            m.constant("VAR_SPACE_XS", R::string_type()),
            m.constant("VAR_SUCCESS", R::string_type()),
            m.constant("VAR_TEXT_2XL", R::string_type()),
            m.constant("VAR_TEXT_LG", R::string_type()),
            m.constant("VAR_TEXT_MD", R::string_type()),
            m.constant("VAR_TEXT_MUTED", R::string_type()),
            m.constant("VAR_TEXT_SM", R::string_type()),
            m.constant("VAR_TEXT_XL", R::string_type()),
            m.constant("VAR_TEXT_XS", R::string_type()),
            m.constant("VAR_WARNING", R::string_type()),
            m.constant("VIEW", R::string_type()),
            m.constant("WARNING", R::string_type()),
        });
}

} // namespace luma::stdlib::detail
