#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_string_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                               const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("byte_length", 1, "(value: string)", R::integer_type(), {p.string}),
            m.fn("capitalize", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("center", 3, "(value: string, width: integer, pad: string)", R::result_string(),
                 {p.string, p.integer, p.string}),
            m.fn("character_at", 2, "(value: string, index: integer)", R::result_string(),
                 {p.string, p.integer}),
            m.fn("characters", 1, "(value: string)", R::array_string(), {p.string}),
            m.fn("chunk", 2, "(value: string, size: integer)", R::array_string(),
                 {p.string, p.integer}),
            m.fn("contains", 2, "(value: string, search: string)", R::boolean_type(),
                 {p.string, p.string}),
            m.fn("contains_ignore_case", 2, "(value: string, search: string)", R::boolean_type(),
                 {p.string, p.string}),
            m.fn("count", 2, "(value: string, search: string)", R::integer_type(),
                 {p.string, p.string}),
            m.fn("dedent", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("delete", 3, "(value: string, start: integer, end: integer)", R::result_string(),
                 {p.string, p.integer, p.integer}),
            m.fn("ends_with", 2, "(value: string, suffix: string)", R::boolean_type(),
                 {p.string, p.string}),
            m.fn("ends_with_any", 2, "(value: string, suffixes: array<string>)", R::boolean_type(),
                 {p.string, R::array(p.string)}),
            m.fn("equals_ignore_case", 2, "(a: string, b: string)", R::boolean_type(),
                 {p.string, p.string}),
            m.fn("format_number", 2, "(value: number, decimals: integer)", R::string_type(),
                 {p.number, p.integer}),
            m.fn("from_bytes", 1, "(bytes: array<integer>)", R::result_string(), {p.array_any}),
            m.fn("from_codepoints", 1, "(codepoints: array<integer>)", R::result_string(),
                 {p.array_any}),
            m.fn("indent", 2, "(value: string, indent: string)", R::string_type(),
                 {p.string, p.string}),
            m.fn("insert", 3, "(value: string, index: integer, text: string)", R::result_string(),
                 {p.string, p.integer, p.string}),
            m.fn("index_of", 2, "(value: string, search: string)", R::result_integer(),
                 {p.string, p.string}),
            m.fn("is_alpha", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_alphanumeric", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_blank", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_digit", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_empty", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_lowercase", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_numeric", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_palindrome", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_uppercase", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("is_whitespace", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("join", 2, "(parts: array<string>, separator: string)", R::string_type(),
                 {p.array_string, p.string}),
            m.fn("last_index_of", 2, "(value: string, search: string)", R::result_integer(),
                 {p.string, p.string}),
            m.fn("levenshtein_distance", 2, "(a: string, b: string)", R::integer_type(),
                 {p.string, p.string}),
            m.fn("length", 1, "(value: string)", R::integer_type(), {p.string}),
            m.fn("lines", 1, "(value: string)", R::array_string(), {p.string}),
            m.fn("lowercase", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("matches", 2, "(value: string, pattern: string)", R::result_boolean(),
                 {p.string, p.string}),
            m.fn("pad_left", 3, "(value: string, length: integer, pad: string)", R::result_string(),
                 {p.string, p.integer, p.string}),
            m.fn("pad_right", 3, "(value: string, length: integer, pad: string)",
                 R::result_string(), {p.string, p.integer, p.string}),
            m.fn("parse_integer", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("parse_number", 1, "(value: string)", R::result_number(), {p.string}),
            m.fn("remove_prefix", 2, "(value: string, prefix: string)", R::string_type(),
                 {p.string, p.string}),
            m.fn("remove_suffix", 2, "(value: string, suffix: string)", R::string_type(),
                 {p.string, p.string}),
            m.fn("repeat", 2, "(value: string, count: integer)", R::result_string(),
                 {p.string, p.integer}),
            m.fn("replace", 3, "(value: string, from: string, to: string)", R::string_type(),
                 {p.string, p.string, p.string}),
            m.fn("replace_all", 3, "(value: string, from: string, to: string)", R::string_type(),
                 {p.string, p.string, p.string}),
            m.fn("replace_range", 4, "(value: string, start: integer, end: integer, text: string)",
                 R::result_string(), {p.string, p.integer, p.integer, p.string}),
            m.fn("reverse", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("split", 2, "(value: string, separator: string)", R::array_string(),
                 {p.string, p.string}),
            m.fn("split_n", 3, "(value: string, separator: string, max: integer)",
                 R::array_string(), {p.string, p.string, p.integer}),
            m.fn("split_whitespace", 1, "(value: string)", R::array_string(), {p.string}),
            m.fn("slug", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("starts_with", 2, "(value: string, prefix: string)", R::boolean_type(),
                 {p.string, p.string}),
            m.fn("starts_with_any", 2, "(value: string, prefixes: array<string>)",
                 R::boolean_type(), {p.string, R::array(p.string)}),
            m.fn("substring", 3, "(value: string, start: integer, end: integer)", R::string_type(),
                 {p.string, p.integer, p.integer}),
            m.fn("template", 2, "(template: string, values: dictionary<string>)", R::string_type(),
                 {p.string, p.dict_any}),
            m.fn("title_case", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("to_bytes", 1, "(value: string)", R::array_integer(), {p.string}),
            m.fn("to_codepoints", 1, "(value: string)", R::array_integer(), {p.string}),
            m.fn("to_camel_case", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("to_kebab_case", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("to_pascal_case", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("to_snake_case", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("trim", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("trim_end", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("trim_start", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("truncate", 2, "(value: string, length: integer)", R::string_type(),
                 {p.string, p.integer}),
            m.fn("uppercase", 1, "(value: string)", R::string_type(), {p.string}),
            m.fn("word_count", 1, "(value: string)", R::integer_type(), {p.string}),
            m.fn("words", 1, "(value: string)", R::array_string(), {p.string}),
            m.fn("wrap", 2, "(value: string, width: integer)", R::string_type(),
                 {p.string, p.integer}),
            m.fn("is_ascii", 1, "(value: string)", R::boolean_type(), {p.string}),
            m.fn("common_prefix", 2, "(a: string, b: string)", R::string_type(),
                 {p.string, p.string}),
            m.fn("common_suffix", 2, "(a: string, b: string)", R::string_type(),
                 {p.string, p.string}),
        });
}

void register_regular_expression_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                           const ParamShorthands& p) {
    append_specs(specs,
                 {
                     m.fn("find", 2, "(text: string, pattern: string)", R::result(named::match()),
                          {p.string, p.string}),
                     m.fn("find_all", 2, "(text: string, pattern: string)",
                          R::result(R::array(named::match())), {p.string, p.string}),
                     m.fn("is_valid", 1, "(pattern: string)", R::boolean_type(), {p.string}),
                     m.fn("count", 2, "(text: string, pattern: string)", R::result_integer(),
                          {p.string, p.string}),
                     m.fn("compile_typed", 1, "(pattern: string)",
                          R::result(R::string_type(), named::regex_error()), {p.string}),
                     m.fn("matches", 2, "(text: string, pattern: string)", R::result_boolean(),
                          {p.string, p.string}),
                     m.fn("replace", 3, "(text: string, pattern: string, replacement: string)",
                          R::result_string(), {p.string, p.string, p.string}),
                     m.fn("replace_all", 3, "(text: string, pattern: string, replacement: string)",
                          R::result_string(), {p.string, p.string, p.string}),
                     m.fn("split", 2, "(text: string, pattern: string)",
                          R::result(R::array(R::string_type())), {p.string, p.string}),
                     // Flag-accepting variants — each takes a trailing
                     // flags: array<RegularExpression.Flags> (CaseInsensitive /
                     // MultiLine / DotAll), mirroring the flagless sibling above.
                     m.fn("matches_with", 3,
                          "(text: string, pattern: string, flags: array<RegularExpression.Flags>)",
                          R::result_boolean(),
                          {p.string, p.string, R::array(named::regex_flags())}),
                     m.fn("find_with", 3,
                          "(text: string, pattern: string, flags: array<RegularExpression.Flags>)",
                          R::result(named::match()),
                          {p.string, p.string, R::array(named::regex_flags())}),
                     m.fn("find_all_with", 3,
                          "(text: string, pattern: string, flags: array<RegularExpression.Flags>)",
                          R::result(R::array(named::match())),
                          {p.string, p.string, R::array(named::regex_flags())}),
                     m.fn("replace_with", 4,
                          "(text: string, pattern: string, replacement: string, flags: "
                          "array<RegularExpression.Flags>)",
                          R::result_string(),
                          {p.string, p.string, p.string, R::array(named::regex_flags())}),
                     m.fn("replace_all_with", 4,
                          "(text: string, pattern: string, replacement: string, flags: "
                          "array<RegularExpression.Flags>)",
                          R::result_string(),
                          {p.string, p.string, p.string, R::array(named::regex_flags())}),
                     m.fn("split_with", 3,
                          "(text: string, pattern: string, flags: array<RegularExpression.Flags>)",
                          R::result(R::array(R::string_type())),
                          {p.string, p.string, R::array(named::regex_flags())}),
                 });
}

} // namespace luma::stdlib::detail
