#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_linear_algebra_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                       const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("add", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number}),
            m.fn("add_matrix", 2, "(a: array<array<number>>, b: array<array<number>>)",
                 R::result(R::array(R::array(R::number_type()))), {p.matrix, p.matrix}),
            m.fn("angle", 2, "(a: array<number>, b: array<number>)", R::result_number(),
                 {p.array_number, p.array_number}),
            m.fn("clamp", 3, "(v: array<number>, lo: number, hi: number)",
                 R::array(R::number_type()), {p.array_number, p.number, p.number}),
            m.fn("columns", 1, "(m: array<array<number>>)", R::integer_type(), {p.matrix}),
            m.fn("cross", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number}),
            m.fn("determinant", 1, "(m: array<array<number>>)", R::result_number(), {p.matrix}),
            m.fn("diagonal", 1, "(v: array<number>)", R::array(R::array(R::number_type())),
                 {p.array_number}),
            m.fn("dimension", 1, "(v: array<number>)", R::integer_type(), {p.array_number}),
            m.fn("distance", 2, "(a: array<number>, b: array<number>)", R::result_number(),
                 {p.array_number, p.array_number}),
            m.fn("dot", 2, "(a: array<number>, b: array<number>)", R::result_number(),
                 {p.array_number, p.array_number}),
            m.fn("hadamard", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number}),
            m.fn("hadamard_matrix", 2, "(a: array<array<number>>, b: array<array<number>>)",
                 R::result(R::array(R::array(R::number_type()))), {p.matrix, p.matrix}),
            m.fn("identity", 1, "(size: integer)", R::array(R::array(R::number_type())),
                 {p.integer}),
            m.fn("inverse", 1, "(m: array<array<number>>)",
                 R::result(R::array(R::array(R::number_type()))), {p.matrix}),
            m.fn("is_diagonal", 1, "(m: array<array<number>>)", R::boolean_type(), {p.matrix}),
            m.fn("is_identity", 1, "(m: array<array<number>>)", R::boolean_type(), {p.matrix}),
            m.fn("is_orthogonal", 2, "(a: array<number>, b: array<number>)", R::boolean_type(),
                 {p.array_number, p.array_number}),
            m.fn("is_square", 1, "(m: array<array<number>>)", R::boolean_type(), {p.matrix}),
            m.fn("is_symmetric", 1, "(m: array<array<number>>)", R::boolean_type(), {p.matrix}),
            m.fn("lerp", 3, "(a: array<number>, b: array<number>, t: number)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number, p.number}),
            m.fn("mean", 1, "(v: array<number>)", R::result_number(), {p.array_number}),
            m.fn("multiply", 2, "(a: array<array<number>>, b: array<array<number>>)",
                 R::result(R::array(R::array(R::number_type()))), {p.matrix, p.matrix}),
            m.fn("multiply_vector", 2, "(m: array<array<number>>, v: array<number>)",
                 R::result(R::array(R::number_type())), {p.matrix, p.array_number}),
            m.fn("negate", 1, "(v: array<number>)", R::array(R::number_type()), {p.array_number}),
            m.fn("norm", 1, "(v: array<number>)", R::number_type(), {p.array_number}),
            m.fn("normalize", 1, "(v: array<number>)", R::result(R::array(R::number_type())),
                 {p.array_number}),
            m.fn("outer", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::array(R::number_type()))), {p.array_number, p.array_number}),
            m.fn("project", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number}),
            m.fn("rank", 1, "(m: array<array<number>>)", R::integer_type(), {p.matrix}),
            m.fn("reject", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number}),
            m.fn("rows", 1, "(m: array<array<number>>)", R::integer_type(), {p.matrix}),
            m.fn("scale", 2, "(v: array<number>, scalar: number)", R::array(R::number_type()),
                 {p.array_number, p.number}),
            m.fn("scale_matrix", 2, "(m: array<array<number>>, scalar: number)",
                 R::array(R::array(R::number_type())), {p.matrix, p.number}),
            m.fn("shape", 1, "(m: array<array<number>>)",
                 R::tuple({R::integer_type(), R::integer_type()}), {p.matrix}),
            m.fn("solve", 2, "(a: array<array<number>>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.matrix, p.array_number}),
            m.fn("subtract", 2, "(a: array<number>, b: array<number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_number}),
            m.fn("sum", 1, "(v: array<number>)", R::number_type(), {p.array_number}),
            m.fn("trace", 1, "(m: array<array<number>>)", R::result_number(), {p.matrix}),
            m.fn("transpose", 1, "(m: array<array<number>>)", R::array(R::array(R::number_type())),
                 {p.matrix}),
            m.fn("unit_vector", 2, "(size: integer, index: integer)", R::array(R::number_type()),
                 {p.integer, p.integer}),
            m.fn("zero_matrix", 2, "(rows: integer, cols: integer)",
                 R::array(R::array(R::number_type())), {p.integer, p.integer}),
            m.fn("zero_vector", 1, "(size: integer)", R::array(R::number_type()), {p.integer}),
        });
}

void register_calculus_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                 const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("convolution", 5,
                 "(f: func(number) -> number, g: func(number) -> number, t: number, a: number, b: "
                 "number)",
                 R::number_type(), {p.func, p.func, p.number, p.number, p.number}),
            m.fn("arc_length", 3, "(a: number, b: number, f: func(number) -> number)",
                 R::number_type(), {p.number, p.number, p.func}),
            m.fn("curl", 2, "(point: array<number>, fields: array<func(array<number>) -> number>)",
                 R::result(R::array(R::number_type())), {p.array_number, p.array_any}),
            m.fn("derivative", 2, "(x: number, f: func(number) -> number)", R::number_type(),
                 {p.number, p.func}),
            m.fn("derivative_with", 3, "(x: number, h: number, f: func(number) -> number)",
                 R::number_type(), {p.number, p.number, p.func}),
            m.fn("differentiate", 1, "(f: func(number) -> number)", R::func_type(), {p.func}),
            m.fn("divergence", 2,
                 "(point: array<number>, fields: array<func(array<number>) -> number>)",
                 R::number_type(), {p.array_number, p.array_any}),
            m.fn("gradient", 2, "(point: array<number>, f: func(array<number>) -> number)",
                 R::array(R::number_type()), {p.array_number, p.func}),
            m.fn("hessian", 2, "(point: array<number>, f: func(array<number>) -> number)",
                 R::array(R::array(R::number_type())), {p.array_number, p.func}),
            m.fn("integrate", 3, "(a: number, b: number, f: func(number) -> number)",
                 R::number_type(), {p.number, p.number, p.func}),
            m.fn("integrate_with", 4,
                 "(a: number, b: number, n: integer, f: func(number) -> number)", R::number_type(),
                 {p.number, p.number, p.integer, p.func}),
            m.fn("jacobian", 2,
                 "(point: array<number>, fields: array<func(array<number>) -> number>)",
                 R::result(R::array(R::array(R::number_type()))), {p.array_number, p.array_any}),
            m.fn("laplacian", 2, "(point: array<number>, f: func(array<number>) -> number)",
                 R::number_type(), {p.array_number, p.func}),
            m.fn("limit", 2, "(x: number, f: func(number) -> number)", R::result_number(),
                 {p.number, p.func}),
            m.fn("maximize", 3, "(a: number, b: number, f: func(number) -> number)",
                 R::tuple({R::number_type(), R::number_type()}), {p.number, p.number, p.func}),
            m.fn("minimize", 3, "(a: number, b: number, f: func(number) -> number)",
                 R::tuple({R::number_type(), R::number_type()}), {p.number, p.number, p.func}),
            m.fn("newton", 2, "(x0: number, f: func(number) -> number)", R::result_number(),
                 {p.number, p.func}),
            m.fn("nth_derivative", 3, "(x: number, n: integer, f: func(number) -> number)",
                 R::number_type(), {p.number, p.integer, p.func}),
            m.fn("partial_derivative", 3,
                 "(point: array<number>, index: integer, f: func(array<number>) -> number)",
                 R::number_type(), {p.array_number, p.integer, p.func}),
            m.fn("product_series", 3, "(start: integer, end: integer, f: func(integer) -> number)",
                 R::number_type(), {p.integer, p.integer, p.func}),
            m.fn("root", 3, "(a: number, b: number, f: func(number) -> number)", R::result_number(),
                 {p.number, p.number, p.func}),
            m.fn("second_derivative", 2, "(x: number, f: func(number) -> number)", R::number_type(),
                 {p.number, p.func}),
            m.fn("sum_series", 3, "(start: integer, end: integer, f: func(integer) -> number)",
                 R::number_type(), {p.integer, p.integer, p.func}),
            m.fn("taylor", 3, "(center: number, degree: integer, f: func(number) -> number)",
                 R::array(R::number_type()), {p.number, p.integer, p.func}),
        });
}

void register_decimal_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("absolute", 1, "(d: decimal)", named::decimal(), {p.decimal}),
            m.fn("add", 2, "(a: decimal, b: decimal)", named::decimal(), {p.decimal, p.decimal}),
            m.fn("compare", 2, "(a: decimal, b: decimal)", R::integer_type(),
                 {p.decimal, p.decimal}),
            m.fn("divide", 3, "(a: decimal, b: decimal, scale: integer)",
                 R::result(named::decimal()), {p.decimal, p.decimal, p.integer}),
            m.fn("divide_typed", 3, "(a: decimal, b: decimal, scale: integer)",
                 R::result(named::decimal(), named::decimal_error()),
                 {p.decimal, p.decimal, p.integer}),
            m.fn("divide_with", 4,
                 "(a: decimal, b: decimal, scale: integer, mode: RoundingMode | string)",
                 R::result(named::decimal()), {p.decimal, p.decimal, p.integer, p.any}),
            m.fn("equals", 2, "(a: decimal, b: decimal)", R::boolean_type(),
                 {p.decimal, p.decimal}),
            m.fn("from_integer", 1, "(value: integer)", named::decimal(), {p.integer}),
            m.fn("from_number", 1, "(value: number)", named::decimal(), {p.number}),
            m.fn("from_string", 1, "(text: string)", R::result(named::decimal()), {p.string}),
            m.fn("from_string_typed", 1, "(text: string)",
                 R::result(named::decimal(), named::decimal_error()), {p.string}),
            m.fn("greater_or_equal", 2, "(a: decimal, b: decimal)", R::boolean_type(),
                 {p.decimal, p.decimal}),
            m.fn("greater_than", 2, "(a: decimal, b: decimal)", R::boolean_type(),
                 {p.decimal, p.decimal}),
            m.fn("is_negative", 1, "(d: decimal)", R::boolean_type(), {p.decimal}),
            m.fn("is_positive", 1, "(d: decimal)", R::boolean_type(), {p.decimal}),
            m.fn("is_zero", 1, "(d: decimal)", R::boolean_type(), {p.decimal}),
            m.fn("less_or_equal", 2, "(a: decimal, b: decimal)", R::boolean_type(),
                 {p.decimal, p.decimal}),
            m.fn("less_than", 2, "(a: decimal, b: decimal)", R::boolean_type(),
                 {p.decimal, p.decimal}),
            m.fn("max", 2, "(a: decimal, b: decimal)", named::decimal(), {p.decimal, p.decimal}),
            m.fn("min", 2, "(a: decimal, b: decimal)", named::decimal(), {p.decimal, p.decimal}),
            m.fn("multiply", 2, "(a: decimal, b: decimal)", named::decimal(),
                 {p.decimal, p.decimal}),
            m.fn("negate", 1, "(d: decimal)", named::decimal(), {p.decimal}),
            m.fn("power", 2, "(base: decimal, exponent: integer)", R::result(named::decimal()),
                 {p.decimal, p.integer}),
            m.fn("product", 1, "(values: array<decimal>)", named::decimal(),
                 {R::array(named::decimal())}),
            m.fn("remainder", 2, "(a: decimal, b: decimal)", R::result(named::decimal()),
                 {p.decimal, p.decimal}),
            m.fn("round", 3, "(d: decimal, places: integer, mode: RoundingMode | string)",
                 named::decimal(), {p.decimal, p.integer, p.any}),
            m.fn("scale", 1, "(d: decimal)", R::integer_type(), {p.decimal}),
            m.fn("sign", 1, "(d: decimal)", R::integer_type(), {p.decimal}),
            m.fn("subtract", 2, "(a: decimal, b: decimal)", named::decimal(),
                 {p.decimal, p.decimal}),
            m.fn("sum", 1, "(values: array<decimal>)", named::decimal(),
                 {R::array(named::decimal())}),
            m.fn("to_integer", 1, "(d: decimal)", R::result_integer(), {p.decimal}),
            m.fn("to_number", 1, "(d: decimal)", R::number_type(), {p.decimal}),
            m.fn("to_string", 1, "(d: decimal)", R::string_type(), {p.decimal}),
        });
}

} // namespace luma::stdlib::detail
