#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_array_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                              const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("all", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_boolean(),
                 {p.array_any, p.func}),
            m.fn("any", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_boolean(),
                 {p.array_any, p.func}),
            m.fn("append", 2, "(arr: array<T>, value: T)", R::array_any(), {p.array_any, p.any}),
            m.fn("binary_search", 2, "(arr: array<T>, value: T)", R::result_integer(),
                 {p.array_any, p.any}),
            m.fn("chunk", 2, "(arr: array<T>, size: integer)",
                 R::result(R::array(R::array(R::any_type()))), {p.array_any, p.integer}),
            m.fn("compact", 1, "(arr: array<T>)", R::array_any(), {p.array_any}),
            m.fn("concat", 2, "(a: array<T>, b: array<T>)", R::array_any(),
                 {p.array_any, p.array_any}),
            m.fn("contains", 2, "(arr: array<T>, value: T)", R::boolean_type(),
                 {p.array_any, p.any}),
            m.fn("count", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_integer(),
                 {p.array_any, p.func}),
            m.fn("count_by", 2, "(arr: array<T>, key: func(T) -> string)",
                 R::dict(R::integer_type()), {p.array_any, p.func}),
            m.fn("drop", 2, "(arr: array<T>, n: integer)", R::array_any(),
                 {p.array_any, p.integer}),
            m.fn("drop_while", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_array_any(),
                 {p.array_any, p.func}),
            m.fn("each", 2, "(arr: array<T>, f: func(T) -> void)", R::result(R::none_type()),
                 {p.array_any, p.func}),
            m.fn("enumerate", 1, "(arr: array<T>)", R::array_any(), {p.array_any}),
            m.fn("filter", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_array_any(),
                 {p.array_any, p.func}),
            m.fn("find", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_any(),
                 {p.array_any, p.func}),
            m.fn("find_index", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_integer(),
                 {p.array_any, p.func}),
            m.fn("find_last", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_any(),
                 {p.array_any, p.func}),
            m.fn("find_last_index", 2, "(arr: array<T>, f: func(T) -> boolean)",
                 R::result_integer(), {p.array_any, p.func}),
            m.fn("first", 1, "(arr: array<T>)", R::result_any(), {p.array_any}),
            m.fn("flat_map", 2, "(arr: array<T>, f: func(T) -> array<U>)", R::result_array_any(),
                 {p.array_any, p.func}),
            m.fn("flatten", 1, "(arr: array<array<T>>)", R::array_any(), {p.array_any}),
            m.fn("get", 2, "(arr: array<T>, index: integer)", R::result_any(),
                 {p.array_any, p.integer}),
            m.fn("group_by", 2, "(arr: array<T>, f: func(T) -> string)",
                 R::result(R::dict(R::array(R::any_type()))), {p.array_any, p.func}),
            m.fn("index_of", 2, "(arr: array<T>, value: T)", R::result_integer(),
                 {p.array_any, p.any}),
            m.fn("insert_at", 3, "(arr: array<T>, index: integer, value: T)", R::result_array_any(),
                 {p.array_any, p.integer, p.any}),
            m.fn("is_empty", 1, "(arr: array<T>)", R::boolean_type(), {p.array_any}),
            m.fn("join", 2, "(arr: array<string>, separator: string)", R::string_type(),
                 {p.array_any, p.string}),
            m.fn("last", 1, "(arr: array<T>)", R::result_any(), {p.array_any}),
            m.fn("length", 1, "(arr: array<T>)", R::integer_type(), {p.array_any}),
            m.fn("map", 2, "(arr: array<T>, f: func(T) -> U)", R::result_array_any(),
                 {p.array_any, p.func}),
            m.fn("max", 1, "(arr: array<integer | number>)", R::result_number(), {p.array_number}),
            m.fn("max_by", 2, "(arr: array<T>, key: func(T) -> number)", R::optional_any(),
                 {p.array_any, p.func}),
            m.fn("min", 1, "(arr: array<integer | number>)", R::result_number(), {p.array_number}),
            m.fn("min_by", 2, "(arr: array<T>, key: func(T) -> number)", R::optional_any(),
                 {p.array_any, p.func}),
            m.fn("partition", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_any(),
                 {p.array_any, p.func}),
            m.fn("pop", 1, "(arr: array<T>)", R::result_any(), {p.array_any}),
            m.fn("push", 2, "(arr: array<T>, value: T)", R::array_any(), {p.array_any, p.any}),
            m.fn("range", 2, "(start: integer, end: integer)",
                 R::result(R::array(R::integer_type())), {p.integer, p.integer}),
            m.fn("reduce", 3, "(arr: array<T>, initial: U, f: func(U, T) -> U)", R::result_any(),
                 {p.array_any, p.any, p.func}),
            m.fn("remove_at", 2, "(arr: array<T>, index: integer)", R::result_any(),
                 {p.array_any, p.integer}),
            m.fn("repeat", 2, "(value: T, count: integer)", R::result_array_any(),
                 {p.any, p.integer}),
            m.fn("reverse", 1, "(arr: array<T>)", R::array_any(), {p.array_any}),
            m.fn("set", 3, "(arr: array<T>, index: integer, value: T)", R::result_array_any(),
                 {p.array_any, p.integer, p.any}),
            m.fn("slice", 3, "(arr: array<T>, start: integer, end: integer)", R::result_array_any(),
                 {p.array_any, p.integer, p.integer}),
            m.fn("sort", 2, "(arr: array<T>, f: func(T, T) -> number)", R::result_array_any(),
                 {p.array_any, p.func}),
            m.fn("sort_by", 2, "(arr: array<T>, f: func(T) -> string | number)",
                 R::result_array_any(), {p.array_any, p.func}),
            m.fn("sum", 1, "(arr: array<integer | number>)", R::result_number(), {p.array_number}),
            m.fn("sum_by", 2, "(arr: array<T>, key: func(T) -> number)", R::number_type(),
                 {p.array_any, p.func}),
            m.fn("take", 2, "(arr: array<T>, n: integer)", R::array_any(),
                 {p.array_any, p.integer}),
            m.fn("take_while", 2, "(arr: array<T>, f: func(T) -> boolean)", R::result_array_any(),
                 {p.array_any, p.func}),
            m.fn("unique", 1, "(arr: array<T>)", R::array_any(), {p.array_any}),
            m.fn("zip", 2, "(a: array<T>, b: array<U>)", R::array_any(),
                 {p.array_any, p.array_any}),
            m.fn("windows", 2, "(arr: array<T>, size: integer)",
                 R::result(R::array(R::array(R::any_type()))), {p.array_any, p.integer}),
            m.fn("scan", 3, "(arr: array<T>, initial: U, f: func(U, T) -> U)",
                 R::result_array_any(), {p.array_any, p.any, p.func}),
            m.fn("intersperse", 2, "(arr: array<T>, separator: T)", R::array_any(),
                 {p.array_any, p.any}),
            m.fn("rotate", 2, "(arr: array<T>, n: integer)", R::array_any(),
                 {p.array_any, p.integer}),
            m.fn("transpose", 1, "(arr: array<array<T>>)",
                 R::result(R::array(R::array(R::any_type()))), {p.array_any}),
        });
}

} // namespace luma::stdlib::detail
