#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_log_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                            const ParamShorthands& p) {
    append_specs(specs, {
                            m.fn("clear_context", 0, "()", R::void_type()),
                            m.fn("debug", 1, "(message: string)", R::void_type(), {p.string}),
                            m.fn("error", 1, "(message: string)", R::void_type(), {p.string}),
                            m.fn("get_level", 0, "()", named::log_level()),
                            m.fn("info", 1, "(message: string)", R::void_type(), {p.string}),
                            m.fn("reset", 0, "()", R::void_type()),
                            m.fn("set_context", 2, "(key: string, value: string)", R::void_type(),
                                 {p.string, p.string}),
                            m.fn("set_format", 1, "(format: string)", R::void_type(), {p.string}),
                            m.fn("set_level", 1, "(level: Level)", R::void_type(), {p.log_level}),
                            m.fn("set_output", 1, "(target: Log.Output | string)", R::result_void(),
                                 {p.any}),
                            m.fn("warn", 1, "(message: string)", R::void_type(), {p.string}),
                        });
}

void register_terminal_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                 const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("background_color", 2, "(color: Terminal.Color | string, text: string)",
                 R::result_string(), {p.any, p.string}),
            m.fn("bell", 0, "()", R::void_type()),
            m.fn("bold", 1, "(text: string)", R::string_type(), {p.string}),
            m.fn("clear_line", 0, "()", R::void_type()),
            m.fn("clear_screen", 0, "()", R::void_type()),
            m.fn("clear_to_end_of_line", 0, "()", R::void_type()),
            m.fn("clear_to_end_of_screen", 0, "()", R::void_type()),
            m.fn("color", 2, "(color: Terminal.Color | string, text: string)", R::result_string(),
                 {p.any, p.string}),
            m.fn("columns", 0, "()", R::integer_type()),
            m.fn("dim", 1, "(text: string)", R::string_type(), {p.string}),
            m.fn("disable_mouse", 0, "()", R::void_type()),
            m.fn("disable_raw_mode", 0, "()", R::void_type()),
            m.fn("enable_mouse", 0, "()", R::result_void()),
            m.fn("enable_raw_mode", 0, "()", R::result_void()),
            m.fn("enter_alternate_screen", 0, "()", R::void_type()),
            m.fn("get_cursor_position", 0, "()", R::result(named::cursor_position())),
            m.fn("get_escape_timeout", 0, "()", R::integer_type()),
            m.fn("get_input", 0, "()", R::result(named::input_event())),
            m.fn("hide_cursor", 0, "()", R::void_type()),
            m.fn("inverse", 1, "(text: string)", R::string_type(), {p.string}),
            m.fn("is_in_raw_mode", 0, "()", R::boolean_type()),
            m.fn("is_mouse_enabled", 0, "()", R::boolean_type()),
            m.fn("is_terminal", 0, "()", R::boolean_type()),
            m.fn("italic", 1, "(text: string)", R::string_type(), {p.string}),
            m.fn("leave_alternate_screen", 0, "()", R::void_type()),
            m.fn("link", 2, "(url: string, text: string)", R::string_type(), {p.string, p.string}),
            m.fn("move_down", 1, "(n: integer)", R::void_type(), {p.integer}),
            m.fn("move_left", 1, "(n: integer)", R::void_type(), {p.integer}),
            m.fn("move_right", 1, "(n: integer)", R::void_type(), {p.integer}),
            m.fn("move_to", 2, "(row: integer, col: integer)", R::result_void(),
                 {p.integer, p.integer}),
            m.fn("move_to_column", 1, "(col: integer)", R::result_void(), {p.integer}),
            m.fn("move_to_row", 1, "(row: integer)", R::result_void(), {p.integer}),
            m.fn("move_up", 1, "(n: integer)", R::void_type(), {p.integer}),
            m.fn("overwrite_line", 1, "(text: string)", R::void_type(), {p.string}),
            m.fn("parse_mouse_event", 1, "(key: string)", R::optional(named::mouse_event()),
                 {p.string}),
            m.fn("parse_key", 1, "(key: string)", named::key(), {p.string}),
            m.fn("read_key", 0, "()", R::result_string()),
            m.fn("read_key_timeout", 1, "(ms: integer)", R::result_string(), {p.integer}),
            m.fn("reset_scroll_region", 0, "()", R::void_type()),
            m.fn("reset_style", 0, "()", R::void_type()),
            m.fn("restore_cursor", 0, "()", R::void_type()),
            m.fn("rgb_background_color", 4, "(r: integer, g: integer, b: integer, text: string)",
                 R::result_string(), {p.integer, p.integer, p.integer, p.string}),
            m.fn("rgb_color", 4, "(r: integer, g: integer, b: integer, text: string)",
                 R::result_string(), {p.integer, p.integer, p.integer, p.string}),
            m.fn("rows", 0, "()", R::integer_type()),
            m.fn("save_cursor", 0, "()", R::void_type()),
            m.fn("scroll_down", 1, "(n: integer)", R::void_type(), {p.integer}),
            m.fn("scroll_up", 1, "(n: integer)", R::void_type(), {p.integer}),
            m.fn("set_escape_timeout", 1, "(ms: integer)", R::void_type(), {p.integer}),
            m.fn("set_scroll_region", 2, "(top: integer, bottom: integer)", R::result_void(),
                 {p.integer, p.integer}),
            m.fn("set_title", 1, "(title: string)", R::void_type(), {p.string}),
            m.fn("show_cursor", 0, "()", R::void_type()),
            m.fn("size", 0, "()", named::size()),
            m.fn("strikethrough", 1, "(text: string)", R::string_type(), {p.string}),
            m.fn("supports_color", 0, "()", R::boolean_type()),
            m.fn("supports_true_color", 0, "()", R::boolean_type()),
            m.fn("test_feed", 1, "(keys: array<string>)", R::void_type(), {p.array_string}),
            m.fn("test_output", 0, "()", R::string_type()),
            m.fn("test_remaining", 0, "()", R::integer_type()),
            m.fn("test_start", 1, "(keys: array<string>)", R::void_type(), {p.array_string}),
            m.fn("test_stop", 0, "()", R::string_type()),
            m.fn("underline", 1, "(text: string)", R::string_type(), {p.string}),
            m.variadic_fn("write", 1, "(parts: string...)", R::void_type(), {p.string}),
        });
}

} // namespace luma::stdlib::detail
