#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_math_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                             const ParamShorthands& p) {
    append_specs(
        specs,
        {
            // Some Math functions document "integer | number" in the params string
            // because both types are accepted by the user. The param_types use p.number
            // (number) because the type checker implicitly coerces integer to number.
            m.fn("absolute", 1, "(value: integer | number)", R::result_number(), {p.number}),
            m.variadic_fn("approximately_equal", 2, "(a: number, b: number, epsilon?: number)",
                          R::boolean_type(), {p.number, p.number}),
            m.fn("arc_cosine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("arc_sine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("arc_tangent", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("angle_difference", 2, "(a: number, b: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("ceil", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("combinations", 2, "(n: integer, k: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("clamp", 3, "(value: number, minimum: number, maximum: number)",
                 R::result_number(), {p.number, p.number, p.number}),
            m.fn("cosine", 1, "(angle: number)", R::result_number(), {p.number}),
            m.fn("degrees", 1, "(radians: number)", R::number_type(), {p.number}),
            m.fn("digit_count", 1, "(value: integer)", R::integer_type(), {p.integer}),
            m.fn("digit_sum", 1, "(value: integer)", R::integer_type(), {p.integer}),
            m.constant("e", R::number_type()),
            m.constant("epsilon", R::number_type()),
            m.fn("error_function", 1, "(x: number)", R::number_type(), {p.number}),
            m.fn("exponential", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("factorial", 1, "(value: integer)", R::result_integer(), {p.integer}),
            m.fn("floor", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("gamma", 1, "(x: number)", R::result_number(), {p.number}),
            m.fn("greatest_common_divisor", 2, "(a: integer, b: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.constant("infinity", R::number_type()),
            m.fn("is_infinite", 1, "(value: number)", R::boolean_type(), {p.number}),
            m.fn("is_finite", 1, "(value: number)", R::boolean_type(), {p.number}),
            m.fn("is_even", 1, "(value: integer)", R::boolean_type(), {p.integer}),
            m.fn("is_not_a_number", 1, "(value: number)", R::boolean_type(), {p.number}),
            m.fn("is_odd", 1, "(value: integer)", R::boolean_type(), {p.integer}),
            m.fn("is_prime", 1, "(value: integer)", R::boolean_type(), {p.integer}),
            m.fn("least_common_multiple", 2, "(a: integer, b: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("linear_interpolation", 3, "(a: number, b: number, t: number)", R::result_number(),
                 {p.number, p.number, p.number}),
            m.fn("log_10", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("log_2", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("log_base", 2, "(value: number, base: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("log_e", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("maximum", 2, "(a: number, b: number)", R::number_type(), {p.number, p.number}),
            m.constant("max_integer", R::integer_type()),
            m.constant("max_number", R::number_type()),
            m.fn("minimum", 2, "(a: number, b: number)", R::number_type(), {p.number, p.number}),
            m.constant("min_integer", R::integer_type()),
            m.constant("min_number", R::number_type()),
            m.constant("nan", R::number_type()),
            m.fn("normalize_angle", 1, "(radians: number)", R::number_type(), {p.number}),
            m.fn("nth_root", 2, "(value: number, n: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("permutations", 2, "(n: integer, k: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.constant("pi", R::number_type()),
            m.fn("power", 2, "(base: number, exponent: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("radians", 1, "(degrees: number)", R::number_type(), {p.number}),
            m.fn("remap", 5,
                 "(value: number, in_minimum: number, in_maximum: number, out_minimum: number, "
                 "out_maximum: number)",
                 R::result_number(), {p.number, p.number, p.number, p.number, p.number}),
            m.fn("remainder", 2, "(a: integer | number, b: integer | number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("round", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("round_to", 2, "(value: number, places: integer)", R::result_number(),
                 {p.number, p.integer}),
            m.fn("sign", 1, "(value: integer | number)", R::integer_type(), {p.number}),
            m.fn("sign_of", 1, "(value: integer | number)", named::sign(), {p.number}),
            m.fn("sine_of", 1, "(angle: Math.Angle)", R::number_type(), {named::angle()}),
            m.fn("sine", 1, "(angle: number)", R::result_number(), {p.number}),
            m.fn("sigmoid", 1, "(x: number)", R::number_type(), {p.number}),
            m.fn("smooth_step", 3, "(edge0: number, edge1: number, x: number)", R::result_number(),
                 {p.number, p.number, p.number}),
            m.fn("square_root", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("sum", 1, "(values: array<number>)", R::result_number(), {p.array_any}),
            m.fn("tangent", 1, "(angle: number)", R::result_number(), {p.number}),
            m.constant("tau", R::number_type()),
            m.fn("to_degrees", 1, "(angle: Math.Angle)", R::number_type(), {named::angle()}),
            m.fn("to_radians", 1, "(angle: Math.Angle)", R::number_type(), {named::angle()}),
            m.fn("truncate", 1, "(value: number)", R::result_integer(), {p.number}),
            m.fn("interval", 2, "(minimum: number, maximum: number)", R::result(named::interval()),
                 {p.number, p.number}),
            m.fn("interval_contains", 2, "(interval: Math.Interval, x: number)", R::boolean_type(),
                 {named::interval(), p.number}),
            m.fn("interval_clamp", 2, "(interval: Math.Interval, x: number)", R::number_type(),
                 {named::interval(), p.number}),
            m.fn("interval_length", 1, "(interval: Math.Interval)", R::number_type(),
                 {named::interval()}),
            m.fn("intervals_overlap", 2, "(a: Math.Interval, b: Math.Interval)", R::boolean_type(),
                 {named::interval(), named::interval()}),
            m.fn("rectangle", 4, "(x: number, y: number, width: number, height: number)",
                 named::rect(), {p.number, p.number, p.number, p.number}),
            m.fn("rectangle_contains", 3, "(rectangle: Math.Rectangle, x: number, y: number)",
                 R::boolean_type(), {named::rect(), p.number, p.number}),
            m.fn("rectangle_intersects", 2, "(a: Math.Rectangle, b: Math.Rectangle)",
                 R::boolean_type(), {named::rect(), named::rect()}),
            m.fn("rectangle_intersection", 2, "(a: Math.Rectangle, b: Math.Rectangle)",
                 R::optional(named::rect()), {named::rect(), named::rect()}),
            m.fn("rectangle_union", 2, "(a: Math.Rectangle, b: Math.Rectangle)", named::rect(),
                 {named::rect(), named::rect()}),
            m.fn("rectangle_center", 1, "(rectangle: Math.Rectangle)", named::vector2(),
                 {named::rect()}),
            m.fn("rectangle_area", 1, "(rectangle: Math.Rectangle)", R::number_type(),
                 {named::rect()}),
            m.fn("vector2", 2, "(x: number, y: number)", named::vector2(), {p.number, p.number}),
            m.fn("circle", 2, "(center: Math.Vector2, radius: number)", named::circle(),
                 {named::vector2(), p.number}),
            m.fn("circle_contains", 2, "(circle: Math.Circle, point: Math.Vector2)",
                 R::boolean_type(), {named::circle(), named::vector2()}),
            m.fn("circle_intersects", 2, "(a: Math.Circle, b: Math.Circle)", R::boolean_type(),
                 {named::circle(), named::circle()}),
            m.fn("circle_rectangle_intersects", 2,
                 "(circle: Math.Circle, rectangle: Math.Rectangle)", R::boolean_type(),
                 {named::circle(), named::rect()}),
            m.fn("arc_tangent2", 2, "(y: number, x: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("hypotenuse", 2, "(x: number, y: number)", R::number_type(), {p.number, p.number}),
            m.fn("log", 2, "(base: number, value: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("cube_root", 1, "(value: number)", R::number_type(), {p.number}),
            m.fn("hyperbolic_sine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("hyperbolic_cosine", 1, "(value: number)", R::result_number(), {p.number}),
            m.fn("hyperbolic_tangent", 1, "(value: number)", R::number_type(), {p.number}),
            m.fn("wrap", 3, "(x: number, low: number, high: number)", R::number_type(),
                 {p.number, p.number, p.number}),
        });
}

void register_converter_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                  const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("character_to_codepoint", 1, "(character: string)", R::result_integer(),
                 {p.string}),
            m.fn("codepoint_to_character", 1, "(code: integer)", R::result_string(), {p.integer}),
            m.fn("from_binary", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("from_hexadecimal", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("from_octal", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("from_roman", 1, "(value: string)", R::result_integer(), {p.string}),
            m.fn("number_to_words", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("ordinal", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_binary", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_boolean", 1, "(value: string)", R::result_boolean(), {p.string}),
            m.fn("to_hexadecimal", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_octal", 1, "(value: integer)", R::string_type(), {p.integer}),
            m.fn("to_integer", 1, "(value: string | number)", R::result_integer(), {p.any}),
            m.fn("to_number", 1, "(value: string | integer)", R::result_number(), {p.any}),
            m.fn("to_roman", 1, "(value: integer)", R::result_string(), {p.integer}),
            m.fn("to_string", 1, "(value: T)", R::string_type(), {p.any}),
        });
}

void register_random_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                               const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("choice", 1, "(array: array<T>)", R::result_any(), {p.any}),
            m.fn("generate_boolean", 0, "()", R::boolean_type(), {}),
            m.fn("generate_bytes", 1, "(n: integer)", R::result(R::array(R::integer_type())),
                 {p.integer}),
            m.fn("generate_integer", 2, "(minimum: integer, maximum: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("generate_number", 0, "()", R::number_type(), {}),
            m.fn("generate_string", 1, "(length: integer)", R::result_string(), {p.integer}),
            m.fn("sample", 2, "(array: array<T>, count: integer)", R::result_array_any(),
                 {p.any, p.integer}),
            m.fn("sample_from", 1, "(distribution: Random.Distribution)", R::result_number(),
                 {named::random_distribution()}),
            m.fn("set_seed", 1, "(seed: integer)", R::void_type(), {p.integer}),
            m.fn("shuffle", 1, "(array: array<T>)", R::array_any(), {p.any}),
            m.fn("generate_uuid", 0, "()", R::string_type(), {}),
            m.fn("parse_uuid", 1, "(uuid: string)", R::result(named::uuid()), {p.string}),
            m.fn("secure_boolean", 0, "()", R::result_boolean(), {}),
            m.fn("secure_bytes", 1, "(n: integer)", R::result(R::array(R::integer_type())),
                 {p.integer}),
            m.fn("secure_integer", 2, "(minimum: integer, maximum: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("secure_number", 0, "()", R::result_number(), {}),
            m.fn("secure_string", 1, "(length: integer)", R::result_string(), {p.integer}),
            m.fn("secure_uuid", 0, "()", R::result_string(), {}),
            m.fn("uuid_typed", 0, "()", named::uuid(), {}),
            m.fn("uuid_to_string", 1, "(uuid: Random.Uuid)", R::string_type(), {named::uuid()}),
        });
}

} // namespace luma::stdlib::detail
