#include "stdlib/stdlib_catalog_internal.hpp"

namespace luma::stdlib::detail {

void register_date_time_functions(std::vector<FunctionSpec>& specs, const ModuleBuilder& m,
                                  const ParamShorthands& p) {
    append_specs(
        specs,
        {
            m.fn("add_days", 2, "(timestamp: number, days: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("add_hours", 2, "(timestamp: number, hours: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("add_months", 2, "(timestamp: number, months: integer)", R::result_number(),
                 {p.number, p.integer}),
            m.fn("add_milliseconds", 2, "(timestamp: number, milliseconds: integer)",
                 R::number_type(), {p.number, p.integer}),
            m.fn("add_minutes", 2, "(timestamp: number, minutes: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("add_seconds", 2, "(timestamp: number, seconds: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("add_weeks", 2, "(timestamp: number, weeks: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("add_years", 2, "(timestamp: number, years: integer)", R::result_number(),
                 {p.number, p.integer}),
            m.fn("add_period", 2, "(timestamp: number, p: DateTime.Period)", R::result_number(),
                 {p.number, named::period()}),
            m.fn("between_dates", 2, "(start: number, end: number)", R::result(named::period()),
                 {p.number, p.number}),
            m.fn("period", 3, "(years: integer, months: integer, days: integer)", named::period(),
                 {p.integer, p.integer, p.integer}),
            m.fn("break_duration", 1, "(total_seconds: number)", named::duration(), {p.number}),
            m.fn("combine", 2, "(date: DateTime.Date, time: DateTime.Time)", R::result_number(),
                 {named::date(), named::time()}),
            m.fn("date", 3, "(year: integer, month: integer, day: integer)",
                 R::result(named::date()), {p.integer, p.integer, p.integer}),
            m.fn("date_of", 1, "(timestamp: number)", R::result(named::date()), {p.number}),
            m.fn("day_of_month", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("day_of_week", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("day_of_year", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("days_in_month", 2, "(year: integer, month: integer)", R::result_integer(),
                 {p.integer, p.integer}),
            m.fn("difference_days", 2, "(start: number, end: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("difference_hours", 2, "(start: number, end: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("difference_months", 2, "(start: number, end: number)", R::result_integer(),
                 {p.number, p.number}),
            m.fn("difference_milliseconds", 2, "(start: number, end: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("difference_minutes", 2, "(start: number, end: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("difference_seconds", 2, "(start: number, end: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("difference_weeks", 2, "(start: number, end: number)", R::number_type(),
                 {p.number, p.number}),
            m.fn("difference_years", 2, "(start: number, end: number)", R::result_integer(),
                 {p.number, p.number}),
            m.fn("end_of_day", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("end_of_hour", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("end_of_month", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("end_of_year", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("from_iso_string", 1, "(iso: string)", R::result_number(), {p.string}),
            m.fn("from_iso_string_typed", 1, "(iso: string)",
                 R::result(R::number_type(), named::datetime_parse_error()), {p.string}),
            m.fn("from_offset", 2, "(timestamp: number, offset: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("from_parts", 6,
                 "(year: integer, month: integer, day: integer, hour: integer, minute: integer, "
                 "second: "
                 "integer)",
                 R::result_number(),
                 {p.integer, p.integer, p.integer, p.integer, p.integer, p.integer}),
            m.fn("from_parts_offset", 7,
                 "(year: integer, month: integer, day: integer, hour: integer, minute: integer, "
                 "second: "
                 "integer, offset: number)",
                 R::result_number(),
                 {p.integer, p.integer, p.integer, p.integer, p.integer, p.integer, p.number}),
            m.fn("format", 2, "(timestamp: number, pattern: string)", R::result_string(),
                 {p.number, p.string}),
            m.fn("format_duration", 1, "(date_time: DateTime.Duration)", R::string_type(),
                 {named::duration()}),
            m.fn("hour", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("interval", 2, "(start: number, end: number)", R::result(named::interval()),
                 {p.number, p.number}),
            m.fn("interval_contains", 2, "(range: DateTime.Interval, timestamp: number)",
                 R::boolean_type(), {named::interval(), p.number}),
            m.fn("interval_duration", 1, "(range: DateTime.Interval)", R::number_type(),
                 {named::interval()}),
            m.fn("intervals_overlap", 2, "(a: DateTime.Interval, b: DateTime.Interval)",
                 R::boolean_type(), {named::interval(), named::interval()}),
            m.fn("is_after", 2, "(a: number, b: number)", R::boolean_type(), {p.number, p.number}),
            m.fn("is_before", 2, "(a: number, b: number)", R::boolean_type(), {p.number, p.number}),
            m.fn("is_leap_year", 1, "(year: integer)", R::boolean_type(), {p.integer}),
            m.fn("is_weekday", 1, "(timestamp: number)", R::boolean_type(), {p.number}),
            m.fn("is_weekend", 1, "(timestamp: number)", R::boolean_type(), {p.number}),
            m.fn("minute", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("month", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("month_from_number", 1, "(n: integer)", R::result(named::month()), {p.integer}),
            m.fn("month_name", 1, "(m: DateTime.Month)", R::string_type(), {p.any}),
            m.fn("month_number", 1, "(m: DateTime.Month)", R::integer_type(), {p.any}),
            m.fn("month_of", 1, "(timestamp: number)", R::result(named::month()), {p.number}),
            m.fn("milliseconds_since_start", 0, "()", R::number_type()),
            m.fn("now_iso_string", 0, "()", R::result_string()),
            m.fn("now_unix", 0, "()", R::number_type()),
            m.fn("offset_hours", 1, "(offset: number)", R::number_type(), {p.number}),
            m.fn("parse", 2, "(text: string, pattern: string)", R::result_number(),
                 {p.string, p.string}),
            m.fn("second", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.fn("start_of_day", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("start_of_hour", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("start_of_month", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("start_of_year", 1, "(timestamp: number)", R::result_number(), {p.number}),
            m.fn("time", 3, "(hour: integer, minute: integer, second: integer)",
                 R::result(named::time()), {p.integer, p.integer, p.integer}),
            m.fn("time_of", 1, "(timestamp: number)", R::result(named::time()), {p.number}),
            m.fn("to_iso_string", 1, "(timestamp: number)", R::result_string(), {p.number}),
            m.fn("to_iso_string_offset", 2, "(timestamp: number, offset: number)",
                 R::result_string(), {p.number, p.number}),
            m.fn("to_offset", 2, "(timestamp: number, offset: number)", R::result_number(),
                 {p.number, p.number}),
            m.fn("to_parts", 1, "(timestamp: number)", R::result(named::time_parts()), {p.number}),
            m.fn("weekday", 1, "(timestamp: number)", R::result(named::weekday()), {p.number}),
            m.fn("weekday_from_number", 1, "(n: integer)", R::result(named::weekday()),
                 {p.integer}),
            m.fn("weekday_name", 1, "(w: DateTime.Weekday)", R::string_type(), {p.any}),
            m.fn("zoned", 2, "(timestamp: number, offset_minutes: integer)",
                 R::result(named::zoned()), {p.number, p.integer}),
            m.fn("zoned_to_iso_string", 1, "(z: DateTime.Zoned)", R::result_string(),
                 {named::zoned()}),
            m.fn("zoned_to_parts", 1, "(z: DateTime.Zoned)", R::result(named::time_parts()),
                 {named::zoned()}),
            m.fn("weekday_number", 1, "(w: DateTime.Weekday)", R::integer_type(), {p.any}),
            m.fn("week_of_year", 1, "(timestamp: number)", R::integer_type(), {p.number}),
            m.fn("year", 1, "(timestamp: number)", R::result_integer(), {p.number}),
            m.constant("seconds_per_minute", R::integer_type()),
            m.constant("seconds_per_hour", R::integer_type()),
            m.constant("seconds_per_day", R::integer_type()),
            m.constant("days_per_week", R::integer_type()),
            m.constant("minutes_per_hour", R::integer_type()),
            m.constant("hours_per_day", R::integer_type()),
            m.constant("months_per_year", R::integer_type()),
            m.constant("milliseconds_per_second", R::integer_type()),
        });
}

} // namespace luma::stdlib::detail
