[package]
name = "tree-sitter-luma"
description = "Luma grammar for tree-sitter"
version = "0.0.1"
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "luma"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/d3v0n5h1r3/luma"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.0.87"

[dev-dependencies]
tree-sitter = "0.26"
streaming-iterator = "0.1"
